import Link from "next/link";
import { Blocks, ExternalLink, KeyRound, ShieldCheck } from "lucide-react";
import { NextJsConnectForm, NextJsConnectionActions } from "@/components/integrations/nextjs-actions";
import { Badge, Card, PageHeader } from "@/components/ui";
import { getNextJsPublishingServerEnv } from "@/lib/config/publishing-env";
import { listNextJsConnections } from "@/lib/publishing/nextjs/nextjs-connections";
import type { SafePublishingConnection } from "@/lib/publishing/types";

export const dynamic = "force-dynamic";
const date = (value:string|null) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle:"medium", timeStyle:"short", timeZone:"UTC" }).format(new Date(value)) : "Not yet";
function ConnectionCard({ connection }: { connection:SafePublishingConnection }) { const connected=connection.status === "connected"; return <Card className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#eef0ff] text-[#6657d9]"><Blocks size={21}/></span><div><h2 className="font-semibold">{connection.storeName || "Next.js website"}</h2>{connection.storeUrl && <Link href={connection.storeUrl} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 break-all text-sm text-[var(--flight-blue)]">{connection.storeUrl}<ExternalLink size={12}/></Link>}</div></div><Badge tone={connected ? "green" : "red"}>{connected ? "Connected" : "Needs attention"}</Badge></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-[var(--muted)]">Connected</dt><dd className="mt-1 font-medium">{date(connection.connectedAt)}</dd></div><div><dt className="text-xs text-[var(--muted)]">Last checked</dt><dd className="mt-1 font-medium">{date(connection.lastCheckedAt)}</dd></div></dl>{connection.errorMessage && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{connection.errorMessage}</p>}<NextJsConnectionActions connectionId={connection.id} connected={connected}/></Card>; }
export default async function NextJsIntegrationPage() { const configured=Boolean(getNextJsPublishingServerEnv()); let connections:SafePublishingConnection[]=[]; let loadError:string|null=null; if(configured) try { connections=await listNextJsConnections(); } catch { loadError="Next.js connections could not be loaded. Check the server configuration and database migration."; } return <><PageHeader eyebrow="Publishing destination" title="Next.js" description="Connect a small, self-hosted Searchhand route in your Next.js app."/><div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card className="p-5 sm:p-6"><div className="flex items-start gap-3"><KeyRound className="mt-0.5 text-[#6657d9]"/><div><h2 className="font-semibold">Connect Next.js</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">Searchhand verifies the route before saving its encrypted bearer token.</p></div></div>{configured ? <div className="mt-5"><NextJsConnectForm/></div> : <p role="alert" className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Add APP_URL, INTEGRATION_ENCRYPTION_KEY and the Supabase server credentials, then apply the Next.js migration.</p>}</Card><Card className="p-5 sm:p-6"><h2 className="font-semibold">Install the adapter</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Add the documented route to the Next.js app you control, set a long random token, deploy it, then paste the site URL and token here.</p><p className="mt-4 text-sm font-semibold text-[var(--flight-blue)]">See `docs/nextjs-integration.md`</p><div className="mt-5 flex gap-2 rounded-xl bg-[#e7f3ed] p-3 text-sm text-[var(--flight-green)]"><ShieldCheck size={17} className="shrink-0"/>The adapter is private, token-protected, and checked over HTTPS.</div></Card></div>{loadError ? <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{loadError}</p> : connections.length ? <div className="mt-5 space-y-4">{connections.map(connection=><ConnectionCard key={connection.id} connection={connection}/>)}</div> : configured ? <p className="mt-5 rounded-xl bg-[#f2f1ec] p-4 text-sm text-[var(--muted)]">No Next.js websites connected yet.</p> : null}</>; }
