import { Badge, Button, Card, Input, PageHeader, Select, Textarea } from "@/components/ui";
const sections=[
  {title:"Project details",body:<div className="grid gap-4 sm:grid-cols-2"><Input label="Project name" defaultValue="Harbour & Pine"/><Input label="Website" defaultValue="https://harbourandpine.co.uk"/></div>},
  {title:"Business profile",body:<div className="grid gap-4"><Input label="Primary service" defaultValue="Bespoke garden rooms"/><Textarea label="Business description" defaultValue="A demonstration business profile for the foundation workspace."/></div>},
  {title:"SEO goals",body:<Select label="Primary goal" defaultValue="leads"><option value="leads">Get more qualified leads</option><option value="visibility">Grow local visibility</option></Select>},
  {title:"Approval preference",body:<Select label="How involved would you like to be?" defaultValue="important"><option value="important">Review important changes</option><option value="all">Review everything</option></Select>},
  {title:"Account",body:<div className="flex items-center justify-between gap-4"><div><p className="font-medium">Alex Morgan</p><p className="text-sm text-[var(--muted)]">Account management is not connected.</p></div><Badge>Workspace owner</Badge></div>},
];
export default function SettingsPage(){return <><PageHeader eyebrow="Workspace preferences" title="Settings" description="A visual foundation for the context and preferences that will guide your SEO employee."/><div className="space-y-5">{sections.map(section=><Card key={section.title} className="p-5 sm:p-6"><h2 className="mb-4 font-semibold">{section.title}</h2>{section.body}</Card>)}<div className="flex items-center gap-3"><Button disabled>Saving unavailable</Button><p className="text-sm text-[var(--muted)]">Forms are visual placeholders and do not save.</p></div></div></>}
