import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { getOptionalUser } from "@/lib/auth/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireGscServerEnv } from "@/lib/config/gsc-env";
import { exchangeGscCode,hashState,listGscProperties,verifyState,GSC_SCOPE } from "@/lib/gsc/oauth";
import { encryptGscRefreshToken } from "@/lib/gsc/token-crypto";

const failure=(request:Request,code:string)=>NextResponse.redirect(new URL(`/app/integrations/google-search-console?error=${encodeURIComponent(code)}`,request.url));
export async function GET(request:Request){const user=await getOptionalUser();if(!user)return failure(request,"authentication_required");const url=new URL(request.url);const state=url.searchParams.get("state");const code=url.searchParams.get("code");if(url.searchParams.get("error"))return failure(request,"google_authorisation_cancelled");if(!state||!code)return failure(request,"invalid_callback");const admin=createAdminClient();const {data:session}=await admin.from("gsc_oauth_sessions").select("*").eq("state_hash",hashState(state)).eq("user_id",user.id).is("consumed_at",null).maybeSingle();if(!session||new Date(session.expires_at)<new Date()||!verifyState(state,session.state_hash))return failure(request,"invalid_or_expired_state");try{const env=requireGscServerEnv();const tokens=await exchangeGscCode(code,session.code_verifier,env);const properties=await listGscProperties(tokens.access_token);const {data:existing}=await admin.from("gsc_connections").select("id,encrypted_refresh_token").eq("website_id",session.website_id).maybeSingle();const connectionId=existing?.id||randomUUID();const encrypted=tokens.refresh_token?encryptGscRefreshToken(tokens.refresh_token,env.GSC_TOKEN_ENCRYPTION_KEY,connectionId):existing?.encrypted_refresh_token;if(!encrypted)return failure(request,"refresh_token_missing");const {error}=await admin.from("gsc_connections").upsert({id:connectionId,workspace_id:session.workspace_id,project_id:session.project_id,website_id:session.website_id,user_id:user.id,encrypted_refresh_token:encrypted,granted_scopes:(tokens.scope||GSC_SCOPE).split(" "),status:"pending",last_error_code:null,last_error_message:null,disconnected_at:null},{onConflict:"website_id"});if(error)throw error;await admin.from("gsc_oauth_sessions").update({connection_id:connectionId,available_properties:properties}).eq("id",session.id);return NextResponse.redirect(new URL(`/app/integrations/google-search-console?session=${session.id}`,request.url))}catch{return failure(request,"google_connection_failed")}}
