import { describe,expect,it } from "vitest";
import { generateRecommendations,scoreRecommendation,type RecommendationInput,type RecommendationCandidate } from "../lib/search-intelligence/recommendation-engine";
const base=():RecommendationInput=>({workspaceId:"workspace",projectId:"project",websiteId:"website",offerings:["Managed digital signage","Installation"],sourceVersions:{crawl:"one"},pages:[{id:"pricing",url:"https://example.com/pricing",title:"Managed signage pricing",indexable:true,pageType:"pricing",primaryTopic:"Managed digital signage pricing",contentCompletenessScore:55,incomingInternalLinks:1,outgoingInternalLinks:2},{id:"service",url:"https://example.com/services/signage",title:"Managed signage",indexable:true,pageType:"service",primaryTopic:"Managed digital signage",contentCompletenessScore:75,incomingInternalLinks:8,outgoingInternalLinks:4},{id:"other",url:"https://example.com/solutions/signage",title:"Signage solutions",indexable:true,pageType:"service",primaryTopic:"Managed digital signage",contentCompletenessScore:65,incomingInternalLinks:3,outgoingInternalLinks:2}],queryPages:[{query:"managed digital signage pricing",pageId:"pricing",pageUrl:"https://example.com/pricing",clicks:5,impressions:481,ctr:5/481,position:11.4,previousClicks:8,previousImpressions:700},{query:"managed signage",pageId:"service",pageUrl:"https://example.com/services/signage",clicks:8,impressions:180,ctr:8/180,position:8,previousClicks:8,previousImpressions:180},{query:"managed signage",pageId:"other",pageUrl:"https://example.com/solutions/signage",clicks:3,impressions:90,ctr:3/90,position:12,previousClicks:3,previousImpressions:90},{query:"rare typo",pageId:null,pageUrl:"https://example.com/old",clicks:0,impressions:2,ctr:0,position:70,previousClicks:0,previousImpressions:0}],issues:[{id:"issue",pageId:"pricing",severity:"error",title:"Broken canonical",issueType:"canonical_invalid",evidence:{}}],links:[]});
describe("opportunity engine",()=>{
  it("creates close-to-page-one, low click-rate, decline, overlap, technical and internal-link work",()=>{const items=generateRecommendations(base());const types=new Set<RecommendationCandidate["recommendationType"]>(items.map(item=>item.recommendationType));const expected:RecommendationCandidate["recommendationType"][]=["improve_existing_page","improve_click_through_rate","investigate_page_decline","merge_pages","technical_fix","add_internal_links","ignore"];for(const type of expected)expect(types.has(type)).toBe(true);expect(items[0].evidence).toBeTruthy();expect(items[0].priorityScore).toBeGreaterThan(0)});
  it("creates a commercial page only when offerings, queries and the page gap agree",()=>{const input=base();input.offerings.push("Video wall installation");input.queryPages.push({query:"video wall installation",pageId:null,pageUrl:"https://example.com/",clicks:1,impressions:120,ctr:1/120,position:24,previousClicks:0,previousImpressions:0});const item=generateRecommendations(input).find(value=>value.recommendationType==="create_commercial_page"&&value.evidence.offering==="Video wall installation");expect(item?.evidence).toMatchObject({offering:"Video wall installation",pageGapConfirmed:true})});
  it("uses stable fingerprints and suppresses duplicates",()=>{const one=generateRecommendations(base());const two=generateRecommendations(base());expect(one.map(item=>item.fingerprint)).toEqual(two.map(item=>item.fingerprint));expect(new Set(one.map(item=>item.fingerprint)).size).toBe(one.length)});
  it("uses a transparent bounded scoring formula",()=>{const score=scoreRecommendation({businessRelevance:.95,searchDemandSignal:.74,rankingOpportunity:.82,expectedImpact:.8,effort:.35,confidence:.88,risk:.1,freshness:1});expect(score).toBeGreaterThan(60);expect(score).toBeLessThanOrEqual(100)});
});
