import "server-only";
import { GSC_READONLY_SCOPE, type GscProperty } from "./oauth";

export class GscDirectError extends Error { constructor(public code:string,message:string,public status=502){super(message)} }
export type GscRefreshToken={refresh_token:string; access_token?:string; expiry_date?:number};
type Config={GOOGLE_GSC_CLIENT_ID:string;GOOGLE_GSC_CLIENT_SECRET:string;GOOGLE_GSC_REDIRECT_URI:string};
const tokenUrl="https://oauth2.googleapis.com/token";
const apiUrl="https://www.googleapis.com/webmasters/v3";

async function googleJson(url:string,init:RequestInit){let response:Response;try{response=await fetch(url,{...init,signal:AbortSignal.timeout(60_000)})}catch{throw new GscDirectError("google_unavailable","Google Search Console is temporarily unavailable.")}const body=await response.json().catch(()=>null) as {error?:string;error_description?:string};if(!response.ok)throw new GscDirectError(response.status===401?"google_reauthentication_required":"google_request_failed",body?.error_description||body?.error||"Google Search Console did not complete the request.",response.status);return body}

export function googleAuthorizationUrl(config:Config,input:{state:string;codeChallenge:string}){const url=new URL("https://accounts.google.com/o/oauth2/v2/auth");url.searchParams.set("client_id",config.GOOGLE_GSC_CLIENT_ID);url.searchParams.set("redirect_uri",config.GOOGLE_GSC_REDIRECT_URI);url.searchParams.set("response_type","code");url.searchParams.set("scope",GSC_READONLY_SCOPE);url.searchParams.set("state",input.state);url.searchParams.set("code_challenge",input.codeChallenge);url.searchParams.set("code_challenge_method","S256");url.searchParams.set("access_type","offline");url.searchParams.set("prompt","consent");return url.toString()}
export async function exchangeGscAuthorizationCode(config:Config,input:{code:string;codeVerifier:string}){const form=new URLSearchParams({code:input.code,code_verifier:input.codeVerifier,client_id:config.GOOGLE_GSC_CLIENT_ID,client_secret:config.GOOGLE_GSC_CLIENT_SECRET,redirect_uri:config.GOOGLE_GSC_REDIRECT_URI,grant_type:"authorization_code"});const token=await googleJson(tokenUrl,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form}) as {access_token?:string;refresh_token?:string;expires_in?:number;scope?:string};if(!token.access_token||!token.refresh_token||token.scope?.split(" ").includes(GSC_READONLY_SCOPE)===false)throw new GscDirectError("invalid_google_scope","Google did not grant the required read-only Search Console access.",403);return{accessToken:token.access_token,refreshToken:{refresh_token:token.refresh_token,access_token:token.access_token,expiry_date:Date.now()+(token.expires_in||3600)*1000}}}
export async function refreshGscAccessToken(config:Config,token:GscRefreshToken){const form=new URLSearchParams({refresh_token:token.refresh_token,client_id:config.GOOGLE_GSC_CLIENT_ID,client_secret:config.GOOGLE_GSC_CLIENT_SECRET,grant_type:"refresh_token"});const refreshed=await googleJson(tokenUrl,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form}) as {access_token?:string;expires_in?:number};if(!refreshed.access_token)throw new GscDirectError("google_reauthentication_required","Google Search Console authorization needs attention.",401);return{accessToken:refreshed.access_token,token:{...token,access_token:refreshed.access_token,expiry_date:Date.now()+(refreshed.expires_in||3600)*1000}}}
export async function listDirectGscProperties(accessToken:string){const body=await googleJson(`${apiUrl}/sites`,{headers:{authorization:`Bearer ${accessToken}`}}) as {siteEntry?:Array<{siteUrl?:string;permissionLevel?:string}>};return(body.siteEntry||[]).flatMap(item=>item.siteUrl&&item.permissionLevel?[{siteUrl:item.siteUrl,permissionLevel:item.permissionLevel} satisfies GscProperty]:[])}
export async function queryDirectGsc(accessToken:string,input:{siteUrl:string;startDate:string;endDate:string;dimensions:string[];startRow:number;rowLimit:number}){const body=await googleJson(`${apiUrl}/sites/${encodeURIComponent(input.siteUrl)}/searchAnalytics/query`,{method:"POST",headers:{authorization:`Bearer ${accessToken}`,"content-type":"application/json"},body:JSON.stringify({startDate:input.startDate,endDate:input.endDate,dimensions:input.dimensions,startRow:input.startRow,rowLimit:input.rowLimit,type:"web",dataState:"final",aggregationType:"auto"})}) as {rows?:Array<{keys?:string[];clicks?:number;impressions?:number;ctr?:number;position?:number}>};return body.rows||[]}
