import type { SupabaseClient } from "@supabase/supabase-js";
import { requireGscServerEnv } from "../config/gsc-env.js";
import { decryptGscRefreshToken,type EncryptedToken } from "./token-crypto.js";
import { GscOAuthError,refreshGscAccessToken } from "./oauth.js";
import { matchGscUrl,type MatchablePage } from "./url-match.js";

type SearchRow={keys?:string[];clicks?:number;impressions?:number;ctr?:number;position?:number};
const date=(value:Date)=>value.toISOString().slice(0,10);
export function gscSyncWindow(type:"initial"|"daily",now=new Date()){const end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-1));const start=new Date(end);start.setUTCDate(start.getUTCDate()-(type==="initial"?89:9));return{startDate:date(start),endDate:date(end)}}
async function queryRows(accessToken:string,propertyUrl:string,startDate:string,endDate:string,dimensions:string[]){const all:SearchRow[]=[];const rowLimit=25000;for(let startRow=0;;startRow+=rowLimit){const response=await fetch(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(propertyUrl)}/searchAnalytics/query`,{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({startDate,endDate,dimensions,type:"web",dataState:"final",rowLimit,startRow}),cache:"no-store"});const payload=await response.json().catch(()=>({})) as {rows?:SearchRow[];error?:{message?:string;code?:number}};if(!response.ok){const error=new Error(payload.error?.message||"Search Console data import failed.");Object.assign(error,{status:response.status});throw error}const rows=payload.rows||[];all.push(...rows);if(rows.length<rowLimit)break}return all}
const metric=(row:SearchRow)=>({clicks:row.clicks||0,impressions:row.impressions||0,ctr:row.ctr||0,position:row.position||0});
async function upsertBatches(client:SupabaseClient,table:string,rows:Record<string,unknown>[],onConflict:string){for(let index=0;index<rows.length;index+=1000){const {error}=await client.from(table).upsert(rows.slice(index,index+1000),{onConflict});if(error)throw error}}
function tokenEnvelope(value:unknown):EncryptedToken{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Stored Search Console credentials are invalid.");const record=value as Record<string,unknown>;if(record.algorithm!=="aes-256-gcm"||record.version!==1||typeof record.ciphertext!=="string"||typeof record.iv!=="string"||typeof record.tag!=="string")throw new Error("Stored Search Console credentials are invalid.");return record as EncryptedToken}

export async function runGscSyncJob(client:SupabaseClient,input:{connection_id:string;sync_type:"initial"|"daily"},jobId:string,heartbeat?:(progress:number,output?:Record<string,unknown>)=>Promise<void>){const env=requireGscServerEnv();const {data:connection,error:connectionError}=await client.from("gsc_connections").select("id,project_id,website_id,property_url,encrypted_refresh_token,status").eq("id",input.connection_id).single();if(connectionError)throw connectionError;if(!connection.property_url||!connection.encrypted_refresh_token)throw new Error("Search Console connection is incomplete.");const window=gscSyncWindow(input.sync_type);const {data:sync,error:syncError}=await client.from("gsc_sync_runs").insert({connection_id:connection.id,project_id:connection.project_id,job_id:jobId,sync_type:input.sync_type,start_date:window.startDate,end_date:window.endDate,status:"running"}).select("id").single();if(syncError)throw syncError;await client.from("gsc_connections").update({status:"syncing",last_synced_at:new Date().toISOString(),last_error_code:null,last_error_message:null}).eq("id",connection.id);
  try{const refresh=decryptGscRefreshToken(tokenEnvelope(connection.encrypted_refresh_token),env.GSC_TOKEN_ENCRYPTION_KEY,connection.id);const token=await refreshGscAccessToken(refresh,env);await heartbeat?.(5,{stage:"authenticated"});const [{data:pages,error:pagesError},daily,queries,pageRows,pairs]=await Promise.all([client.from("website_pages").select("id,normalised_url,final_url,latest_canonical_url").eq("website_id",connection.website_id),queryRows(token.access_token,connection.property_url,window.startDate,window.endDate,["date"]),queryRows(token.access_token,connection.property_url,window.startDate,window.endDate,["date","query"]),queryRows(token.access_token,connection.property_url,window.startDate,window.endDate,["date","page"]),queryRows(token.access_token,connection.property_url,window.startDate,window.endDate,["date","query","page"])]);if(pagesError)throw pagesError;await heartbeat?.(35,{stage:"downloaded",rows:daily.length+queries.length+pageRows.length+pairs.length});const matchable=(pages||[]) as MatchablePage[];
    await upsertBatches(client,"gsc_daily_metrics",daily.map(row=>({connection_id:connection.id,date:row.keys?.[0],search_type:"web",...metric(row)})),"connection_id,date,search_type");
    await upsertBatches(client,"gsc_query_metrics",queries.map(row=>({connection_id:connection.id,date:row.keys?.[0],query:row.keys?.[1]||"",device:"all",country:"all",...metric(row)})),"connection_id,date,query,device,country");
    await upsertBatches(client,"gsc_page_metrics",pageRows.map(row=>{const raw=row.keys?.[1]||"";const matched=matchGscUrl(raw,matchable);return{connection_id:connection.id,date:row.keys?.[0],page_url:raw,normalised_page_url:matched.normalised,website_page_id:matched.pageId,...metric(row)}}),"connection_id,date,page_url");
    await upsertBatches(client,"gsc_query_page_metrics",pairs.map(row=>{const raw=row.keys?.[2]||"";const matched=matchGscUrl(raw,matchable);return{connection_id:connection.id,date:row.keys?.[0],query:row.keys?.[1]||"",page_url:raw,normalised_page_url:matched.normalised,website_page_id:matched.pageId,...metric(row)}}),"connection_id,date,query,page_url");
    const rowsImported=daily.length+queries.length+pageRows.length+pairs.length;const now=new Date().toISOString();await Promise.all([client.from("gsc_sync_runs").update({status:"completed",progress:100,rows_imported:rowsImported,completed_at:now,cursor:{start_date:window.startDate,end_date:window.endDate}}).eq("id",sync.id),client.from("gsc_connections").update({status:"connected",last_synced_at:now,last_successful_sync_at:now,sync_cursor:{last_start_date:window.startDate,last_end_date:window.endDate},last_error_code:null,last_error_message:null}).eq("id",connection.id),client.from("activities").insert({project_id:connection.project_id,activity_type:"search_data_imported",title:"Search data imported",description:`Searchhand imported ${rowsImported.toLocaleString()} measured Search Console rows for ${window.startDate} to ${window.endDate}.`,status:"completed",related_entity_type:"gsc_connection",related_entity_id:connection.id,metadata:{sync_type:input.sync_type,start_date:window.startDate,end_date:window.endDate,rows_imported:rowsImported}})]);await client.from("seo_jobs").insert({project_id:connection.project_id,job_type:"generate_seo_recommendations",status:"queued",priority:80,progress:0,input_payload:{website_id:connection.website_id,connection_id:connection.id,gsc_window:window},max_attempts:3,dedupe_key:`recommendations:gsc:${connection.id}:${window.endDate}`,next_attempt_at:now,required_capability:"search_intelligence"});return{rowsImported,...window};
  }catch(error){const permanent=error instanceof GscOAuthError&&error.code==="invalid_grant";const code=permanent?"refresh_token_invalid":"gsc_sync_failed";const message=error instanceof Error?error.message:"Search Console sync failed.";await Promise.all([client.from("gsc_sync_runs").update({status:"failed",error_code:code,error_message:message.slice(0,1000),completed_at:new Date().toISOString()}).eq("id",sync.id),client.from("gsc_connections").update({status:permanent?"needs_reauthentication":"error",last_error_code:code,last_error_message:message.slice(0,1000)}).eq("id",connection.id)]);throw error}
}
