import type { SupabaseClient } from "@supabase/supabase-js";
import { requireGscServerEnv } from "../config/gsc-env.js";
import {
  GscComposioError,
  getVerifiedGscAccount,
  queryGscSearchAnalytics,
  type ComposioGscIdentity,
  type GscSearchRow,
} from "./composio-worker.js";
import { matchGscUrl,type MatchablePage } from "./url-match.js";
import { gscSyncWindow } from "./sync-window.js";

async function queryRows(identity:ComposioGscIdentity,propertyUrl:string,startDate:string,endDate:string,dimensions:string[]){const all:GscSearchRow[]=[];const rowLimit=5000;for(let startRow=0;;startRow+=rowLimit){const rows=await queryGscSearchAnalytics(identity,{siteUrl:propertyUrl,startDate,endDate,dimensions,startRow,rowLimit});all.push(...rows);if(rows.length<rowLimit)break}return all}
const metric=(row:GscSearchRow)=>({clicks:row.clicks||0,impressions:row.impressions||0,ctr:row.ctr||0,position:row.position||0});
async function upsertBatches(client:SupabaseClient,table:string,rows:Record<string,unknown>[],onConflict:string){for(let index=0;index<rows.length;index+=1000){const {error}=await client.from(table).upsert(rows.slice(index,index+1000),{onConflict});if(error)throw error}}

export async function runGscSyncJob(client:SupabaseClient,input:{connection_id:string;sync_type:"initial"|"daily"},jobId:string,heartbeat?:(progress:number,output?:Record<string,unknown>)=>Promise<void>){const env=requireGscServerEnv();const {data:connection,error:connectionError}=await client.from("gsc_connections").select("id,project_id,website_id,property_url,status,connection_method,composio_user_id,composio_connected_account_id,composio_auth_config_id").eq("id",input.connection_id).single();if(connectionError)throw connectionError;if(!connection.property_url||connection.connection_method!=="composio"||!connection.composio_user_id||!connection.composio_connected_account_id||connection.composio_auth_config_id!==env.COMPOSIO_GSC_AUTH_CONFIG_ID)throw new GscComposioError("connection_incomplete","Search Console connection is incomplete.",409);const identity={userId:connection.composio_user_id,connectedAccountId:connection.composio_connected_account_id,authConfigId:connection.composio_auth_config_id};const window=gscSyncWindow(input.sync_type);const {data:sync,error:syncError}=await client.from("gsc_sync_runs").insert({connection_id:connection.id,project_id:connection.project_id,job_id:jobId,sync_type:input.sync_type,start_date:window.startDate,end_date:window.endDate,status:"running"}).select("id").single();if(syncError)throw syncError;await client.from("gsc_connections").update({status:"syncing",last_synced_at:new Date().toISOString(),last_error_code:null,last_error_message:null}).eq("id",connection.id);
  try{const verified=await getVerifiedGscAccount(identity);if(verified.status!=="connected")throw new GscComposioError("connection_not_active","Google Search Console authorization needs attention.",401);await heartbeat?.(5,{stage:"authenticated_via_composio"});const [{data:pages,error:pagesError},daily,queries,pageRows,pairs]=await Promise.all([client.from("website_pages").select("id,normalised_url,final_url,latest_canonical_url").eq("website_id",connection.website_id),queryRows(identity,connection.property_url,window.startDate,window.endDate,["date"]),queryRows(identity,connection.property_url,window.startDate,window.endDate,["date","query"]),queryRows(identity,connection.property_url,window.startDate,window.endDate,["date","page"]),queryRows(identity,connection.property_url,window.startDate,window.endDate,["date","query","page"])]);if(pagesError)throw pagesError;await heartbeat?.(35,{stage:"downloaded",rows:daily.length+queries.length+pageRows.length+pairs.length});const matchable=(pages||[]) as MatchablePage[];
    await upsertBatches(client,"gsc_daily_metrics",daily.map(row=>({connection_id:connection.id,date:row.keys?.[0],search_type:"web",...metric(row)})),"connection_id,date,search_type");
    await upsertBatches(client,"gsc_query_metrics",queries.map(row=>({connection_id:connection.id,date:row.keys?.[0],query:row.keys?.[1]||"",device:"all",country:"all",...metric(row)})),"connection_id,date,query,device,country");
    await upsertBatches(client,"gsc_page_metrics",pageRows.map(row=>{const raw=row.keys?.[1]||"";const matched=matchGscUrl(raw,matchable);return{connection_id:connection.id,date:row.keys?.[0],page_url:raw,normalised_page_url:matched.normalised,website_page_id:matched.pageId,...metric(row)}}),"connection_id,date,page_url");
    await upsertBatches(client,"gsc_query_page_metrics",pairs.map(row=>{const raw=row.keys?.[2]||"";const matched=matchGscUrl(raw,matchable);return{connection_id:connection.id,date:row.keys?.[0],query:row.keys?.[1]||"",page_url:raw,normalised_page_url:matched.normalised,website_page_id:matched.pageId,...metric(row)}}),"connection_id,date,query,page_url");
    const rowsImported=daily.length+queries.length+pageRows.length+pairs.length;const now=new Date().toISOString();await Promise.all([client.from("gsc_sync_runs").update({status:"completed",progress:100,rows_imported:rowsImported,completed_at:now,cursor:{start_date:window.startDate,end_date:window.endDate}}).eq("id",sync.id),client.from("gsc_connections").update({status:"connected",last_synced_at:now,last_successful_sync_at:now,sync_cursor:{last_start_date:window.startDate,last_end_date:window.endDate},last_error_code:null,last_error_message:null}).eq("id",connection.id),client.from("activities").insert({project_id:connection.project_id,activity_type:"search_data_imported",title:"Search data imported",description:`Searchhand imported ${rowsImported.toLocaleString()} measured Search Console rows for ${window.startDate} to ${window.endDate}.`,status:"completed",related_entity_type:"gsc_connection",related_entity_id:connection.id,metadata:{sync_type:input.sync_type,start_date:window.startDate,end_date:window.endDate,rows_imported:rowsImported,connection_method:"composio"}})]);await client.from("seo_jobs").insert({project_id:connection.project_id,job_type:"generate_seo_recommendations",status:"queued",priority:80,progress:0,input_payload:{website_id:connection.website_id,connection_id:connection.id,gsc_window:window},max_attempts:3,dedupe_key:`recommendations:gsc:${connection.id}:${window.endDate}`,next_attempt_at:now,required_capability:"search_intelligence"});return{rowsImported,...window};
  }catch(error){const permanent=error instanceof GscComposioError&&["connection_not_active","connection_identity_mismatch","connection_incomplete"].includes(error.code);const code=permanent?"composio_connection_invalid":"gsc_sync_failed";const message=error instanceof Error?error.message:"Search Console sync failed.";await Promise.all([client.from("gsc_sync_runs").update({status:"failed",error_code:code,error_message:message.slice(0,1000),completed_at:new Date().toISOString()}).eq("id",sync.id),client.from("gsc_connections").update({status:permanent?"needs_reauthentication":"error",last_error_code:code,last_error_message:message.slice(0,1000)}).eq("id",connection.id)]);throw error}
}
