import { createHash,randomBytes,timingSafeEqual } from "node:crypto";
import type { GscServerEnv } from "../config/gsc-env.js";
export const GSC_SCOPE="https://www.googleapis.com/auth/webmasters.readonly";
export function createGscOAuthProof(){const state=randomBytes(32).toString("base64url");const verifier=randomBytes(48).toString("base64url");const challenge=createHash("sha256").update(verifier).digest("base64url");return{state,stateHash:hashState(state),verifier,challenge}}
export function hashState(state:string){return createHash("sha256").update(state).digest("hex")}
export function verifyState(state:string,expectedHash:string){const actual=Buffer.from(hashState(state),"hex");const expected=Buffer.from(expectedHash,"hex");return actual.length===expected.length&&timingSafeEqual(actual,expected)}
export function buildGscAuthorizationUrl(env:GscServerEnv,proof:{state:string;challenge:string}){const url=new URL("https://accounts.google.com/o/oauth2/v2/auth");url.search=new URLSearchParams({client_id:env.GOOGLE_GSC_CLIENT_ID,redirect_uri:env.GOOGLE_GSC_REDIRECT_URI,response_type:"code",scope:GSC_SCOPE,access_type:"offline",prompt:"consent",include_granted_scopes:"false",state:proof.state,code_challenge:proof.challenge,code_challenge_method:"S256"}).toString();return url.toString()}
type TokenResponse={access_token:string;expires_in:number;refresh_token?:string;scope?:string;token_type:string};
export class GscOAuthError extends Error{constructor(public code:string,message:string){super(message);this.name="GscOAuthError"}}
async function tokenRequest(values:Record<string,string>){const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(values),cache:"no-store"});const payload=await response.json().catch(()=>({})) as Partial<TokenResponse>&{error?:string;error_description?:string};if(!response.ok||!payload.access_token)throw new GscOAuthError(payload.error||"token_exchange_failed",payload.error_description||"Google token exchange failed.");return payload as TokenResponse}
export function exchangeGscCode(code:string,verifier:string,env:GscServerEnv){return tokenRequest({client_id:env.GOOGLE_GSC_CLIENT_ID,client_secret:env.GOOGLE_GSC_CLIENT_SECRET,code,code_verifier:verifier,grant_type:"authorization_code",redirect_uri:env.GOOGLE_GSC_REDIRECT_URI})}
export function refreshGscAccessToken(refreshToken:string,env:GscServerEnv){return tokenRequest({client_id:env.GOOGLE_GSC_CLIENT_ID,client_secret:env.GOOGLE_GSC_CLIENT_SECRET,refresh_token:refreshToken,grant_type:"refresh_token"})}
export type GscProperty={siteUrl:string;permissionLevel:string};
export async function listGscProperties(accessToken:string):Promise<GscProperty[]>{const response=await fetch("https://www.googleapis.com/webmasters/v3/sites",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});const payload=await response.json().catch(()=>({})) as {siteEntry?:GscProperty[];error?:{message?:string}};if(!response.ok)throw new Error(payload.error?.message||"Search Console properties could not be listed.");return(payload.siteEntry||[]).filter(item=>["siteOwner","siteFullUser","siteRestrictedUser"].includes(item.permissionLevel))}
