"use client";
import { useEffect, useState } from "react";
import { Card, Input, Select, Textarea } from "@/components/ui";
import { OnboardingNavigation } from "@/components/onboarding/onboarding-navigation";
import { StepIntro } from "@/components/onboarding/onboarding-shell";
import { businessSchema } from "@/lib/onboarding/schema";
import type { AudienceScope, BrandTone, OnboardingData } from "@/lib/onboarding/types";

type Values={businessName:string;businessDescription:string;industry:string;servicesText:string;targetCustomer:string;location:string;audienceScope:AudienceScope;primaryConversion:string;brandTone:BrandTone};
const initial=(data:OnboardingData):Values=>({businessName:data.businessName,businessDescription:data.businessDescription,industry:data.industry,servicesText:data.services.join(", "),targetCustomer:data.targetCustomer,location:data.location,audienceScope:data.audienceScope,primaryConversion:data.primaryConversion,brandTone:data.brandTone});

export function BusinessStep({ data, update, back, next }: { data: OnboardingData; update: (patch: Partial<OnboardingData>) => void; back:()=>void; next:()=>void }) {
  const [values,setValues]=useState<Values>(()=>initial(data));const [errors,setErrors]=useState<Record<string,string>>({});const [status,setStatus]=useState<"loading"|"waiting"|"ready"|"unavailable"|"ai_not_configured">("loading");
  useEffect(()=>{let active=true;const load=async()=>{const response=await fetch("/api/onboarding/profile",{cache:"no-store"});const payload=await response.json().catch(()=>null);if(!active)return;if(payload?.status==="ready"&&payload.profile){const profile=payload.profile;setValues(current=>({businessName:current.businessName||profile.businessName,businessDescription:current.businessDescription||profile.businessDescription,industry:current.industry||profile.industry,servicesText:current.servicesText||profile.services.join(", "),targetCustomer:current.targetCustomer||profile.targetCustomer,location:current.location||profile.location,audienceScope:current.audienceScope||profile.audienceScope,primaryConversion:current.primaryConversion||profile.primaryConversion,brandTone:current.brandTone||profile.brandTone}));setStatus("ready");return}setStatus(payload?.status||"unavailable")};void load();const timer=window.setInterval(load,5000);return()=>{active=false;window.clearInterval(timer)}},[]);
  function submit(event:React.FormEvent){event.preventDefault();const result=businessSchema.safeParse(values);if(!result.success){setErrors(Object.fromEntries(result.error.issues.map(issue=>[String(issue.path[0]),issue.message])));return;}const {servicesText,...rest}=result.data;update({...rest,services:servicesText.split(",").map(item=>item.trim()).filter(Boolean)});next();}
  const message=status==="ready"?"Draft generated from the public pages Searchhand crawled. Review and edit every field before continuing.":status==="waiting"||status==="loading"?"Searchhand is still reading public pages. This form will fill only when enough website content is available.":status==="ai_not_configured"?"Website pages are being crawled, but AI profile generation is not configured yet. Add OPENAI_API_KEY on Render, then refresh this page.":"Searchhand could not produce a profile from the available pages. Enter the verified details below.";
  return <form onSubmit={submit}><StepIntro eyebrow="Business understanding" title="Confirm what Searchhand found on your website." description="No name-based assumptions are used. The draft is generated only from publicly crawled website content."/><Card className="mx-auto max-w-3xl p-5 sm:p-7"><p className="mb-5 rounded-xl bg-[var(--accent-soft)] p-3 text-sm text-[var(--accent-strong)]">{message}</p><div className="grid gap-5 sm:grid-cols-2"><Input label="Business name" value={values.businessName} onChange={event=>setValues({...values,businessName:event.target.value})} error={errors.businessName}/><Input label="Industry" value={values.industry} onChange={event=>setValues({...values,industry:event.target.value})} error={errors.industry}/><div className="sm:col-span-2"><Textarea label="Short business description" value={values.businessDescription} onChange={event=>setValues({...values,businessDescription:event.target.value})} error={errors.businessDescription}/></div><div className="sm:col-span-2"><Input label="Main products or services" hint="Separate several services with commas." value={values.servicesText} onChange={event=>setValues({...values,servicesText:event.target.value})} error={errors.servicesText}/></div><Input label="Target customer" value={values.targetCustomer} onChange={event=>setValues({...values,targetCustomer:event.target.value})} error={errors.targetCustomer}/><Input label="Main location" value={values.location} onChange={event=>setValues({...values,location:event.target.value})}/><Select label="Audience scope" value={values.audienceScope} onChange={event=>setValues({...values,audienceScope:event.target.value as AudienceScope})}><option value="local">Local</option><option value="national">National</option><option value="international">International</option></Select><Select label="Primary conversion goal" value={values.primaryConversion} onChange={event=>setValues({...values,primaryConversion:event.target.value})}>{["Purchase","Start a trial","Book a call","Request a quote","Make a reservation","Visit a location","Contact the business"].map(option=><option key={option}>{option}</option>)}</Select><Select label="Brand tone" value={values.brandTone} onChange={event=>setValues({...values,brandTone:event.target.value as BrandTone})}>{["Professional","Friendly","Expert","Direct","Premium","Approachable"].map(option=><option key={option}>{option}</option>)}</Select></div></Card><OnboardingNavigation back={back} nextType="submit" nextLabel="Confirm business profile"/></form>;
}
