"use client";
import { useState } from "react";
import { Card, Input, Select, Textarea } from "@/components/ui";
import { OnboardingNavigation } from "@/components/onboarding/onboarding-navigation";
import { StepIntro } from "@/components/onboarding/onboarding-shell";
import { businessSchema } from "@/lib/onboarding/schema";
import { inferBusinessProfile } from "@/lib/mock/onboarding";
import type { AudienceScope, BrandTone, OnboardingData } from "@/lib/onboarding/types";

export function BusinessStep({ data, update, back, next }: { data: OnboardingData; update: (patch: Partial<OnboardingData>) => void; back:()=>void; next:()=>void }) {
  const inferred=inferBusinessProfile(data);
  const [values,setValues]=useState({businessName:data.businessName,businessDescription:data.businessDescription||inferred.businessDescription,industry:data.industry||inferred.industry,servicesText:(data.services.length?data.services:inferred.services).join(", "),targetCustomer:data.targetCustomer||inferred.targetCustomer,location:data.location,audienceScope:data.audienceScope,primaryConversion:data.businessDescription?data.primaryConversion:inferred.primaryConversion,brandTone:data.businessDescription?data.brandTone:inferred.brandTone});
  const [errors,setErrors]=useState<Record<string,string>>({});
  function submit(event:React.FormEvent){event.preventDefault();const result=businessSchema.safeParse(values);if(!result.success){setErrors(Object.fromEntries(result.error.issues.map(issue=>[String(issue.path[0]),issue.message])));return;}const {servicesText,...rest}=result.data;update({...rest,services:servicesText.split(",").map(item=>item.trim()).filter(Boolean)});next();}
  return <form onSubmit={submit}><StepIntro eyebrow="Business understanding" title="Here is what we understand about your business." description="Confirm this so future SEO work stays relevant to your customers. Everything remains editable."/><Card className="mx-auto max-w-3xl p-5 sm:p-7"><p className="mb-5 rounded-xl bg-[var(--accent-soft)] p-3 text-sm text-[var(--accent-strong)]"><strong>Initial preview:</strong> Example content was selected using only the words in your business name and website address.</p><div className="grid gap-5 sm:grid-cols-2"><Input label="Business name" value={values.businessName} onChange={event=>setValues({...values,businessName:event.target.value})} error={errors.businessName}/><Input label="Industry" value={values.industry} onChange={event=>setValues({...values,industry:event.target.value})} error={errors.industry}/><div className="sm:col-span-2"><Textarea label="Short business description" value={values.businessDescription} onChange={event=>setValues({...values,businessDescription:event.target.value})} error={errors.businessDescription}/></div><div className="sm:col-span-2"><Input label="Main products or services" hint="Separate several services with commas." value={values.servicesText} onChange={event=>setValues({...values,servicesText:event.target.value})} error={errors.servicesText}/></div><Input label="Target customer" value={values.targetCustomer} onChange={event=>setValues({...values,targetCustomer:event.target.value})} error={errors.targetCustomer}/><Input label="Main location" value={values.location} onChange={event=>setValues({...values,location:event.target.value})}/><Select label="Audience scope" value={values.audienceScope} onChange={event=>setValues({...values,audienceScope:event.target.value as AudienceScope})}><option value="local">Local</option><option value="national">National</option><option value="international">International</option></Select><Select label="Primary conversion goal" value={values.primaryConversion} onChange={event=>setValues({...values,primaryConversion:event.target.value})}>{["Purchase","Start a trial","Book a call","Request a quote","Make a reservation","Visit a location","Contact the business"].map(option=><option key={option}>{option}</option>)}</Select><Select label="Brand tone" value={values.brandTone} onChange={event=>setValues({...values,brandTone:event.target.value as BrandTone})}>{["Professional","Friendly","Expert","Direct","Premium","Approachable"].map(option=><option key={option}>{option}</option>)}</Select></div></Card><OnboardingNavigation back={back} nextType="submit" nextLabel="Looks right"/></form>;
}
