"use client";
import { CheckCircle2, Database, UserRound } from "lucide-react";
import { Badge, Card } from "@/components/ui";
import { OnboardingNavigation } from "@/components/onboarding/onboarding-navigation";
import { StepIntro } from "@/components/onboarding/onboarding-shell";
import { createInitialPlan } from "@/lib/mock/dashboard";
import type { OnboardingData } from "@/lib/onboarding/types";

export function PlanStep({data,back,next}:{data:OnboardingData;back:()=>void;next:()=>void}){const plan=createInitialPlan(data);return <><StepIntro eyebrow="Prepared from your answers" title="Here is your initial SEO plan." description="A practical starting point based on your business profile—not external SEO, traffic or ranking data."/><div className="mx-auto max-w-4xl"><div className="mb-6 grid gap-3 sm:grid-cols-3"><Card className="flex items-center gap-3 p-4"><CheckCircle2 className="text-[var(--success)]" size={20}/><div><p className="text-xl font-semibold">8</p><p className="text-xs text-[var(--muted)]">initial actions prepared</p></div></Card><Card className="flex items-center gap-3 p-4"><Database className="text-[var(--warning)]" size={20}/><div><p className="text-xl font-semibold">3</p><p className="text-xs text-[var(--muted)]">need real search data</p></div></Card><Card className="flex items-center gap-3 p-4"><UserRound className="text-[#55728d]" size={20}/><div><p className="text-xl font-semibold">2</p><p className="text-xs text-[var(--muted)]">may require your input</p></div></Card></div><div className="grid gap-4 lg:grid-cols-2">{plan.map(section=><Card key={section.category} className="p-5"><h2 className="font-semibold">{section.category}</h2><div className="mt-4 space-y-4">{section.items.map(item=><div key={item.title} className="border-t border-[var(--border)] pt-4 first:border-0 first:pt-0"><div className="flex flex-wrap gap-2"><Badge tone={item.needsData?"amber":"green"}>{item.status}</Badge><Badge>{item.impact} impact</Badge><Badge>{item.effort} effort</Badge></div><h3 className="mt-2 font-medium">{item.title}</h3><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{item.explanation}</p><p className="mt-2 text-xs font-medium text-[var(--muted)]">{item.confidence}</p></div>)}</div></Card>)}</div></div><OnboardingNavigation back={back} onNext={next} nextLabel="Start my SEO employee"/></>}
