"use client";
import { motion, useReducedMotion } from "framer-motion";
import { Check, CheckCircle2, CircleDot } from "lucide-react";
import { StepIntro } from "@/components/onboarding/onboarding-shell";
import { Button, Card } from "@/components/ui";
import type { OnboardingData } from "@/lib/onboarding/types";

export function ReadyStep({data,back,finish}:{data:OnboardingData;back:()=>void;finish:()=>void}){
  const reduce=useReducedMotion();const completed=["Website added","Business profile confirmed","SEO goals selected",data.competitors.length?`${data.competitors.length} competitors added`:"Competitor step reviewed","Initial opportunities prepared","Approval preference saved"];
  return <><StepIntro eyebrow="Flight plan prepared" title="Your Flight Deck is ready." description="Your destination, pre-flight findings and starting routes are ready in one workspace."/><div className="mx-auto grid max-w-4xl gap-5 lg:grid-cols-[1fr_.9fr]"><Card className="p-6"><motion.div initial={reduce?false:{scale:.75,opacity:0}} animate={{scale:1,opacity:1}} className="grid h-14 w-14 place-items-center rounded-full bg-[var(--flight-orange)] text-white"><Check size={27}/></motion.div><h2 className="mt-5 text-xl font-semibold">Flight Deck prepared for {data.businessName}</h2><div className="mt-5 space-y-3">{completed.map((item,index)=><motion.div key={item} initial={reduce?false:{opacity:0,x:8}} animate={{opacity:1,x:0}} transition={{delay:reduce?0:index*.06}} className="flex items-center gap-3"><CheckCircle2 size={18} className="shrink-0 text-[var(--flight-green)]"/><span className="text-sm">{item}</span></motion.div>)}</div></Card><Card className="border-[#c1d3ca] bg-[#eaf5ef] p-6"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-[var(--flight-green)]"/><p className="font-semibold">Agent status: Ready</p></div><h2 className="mt-5 font-semibold">First routes to evaluate</h2><div className="mt-3 space-y-3">{["Review website structure","Prepare topic opportunities","Organise confirmed competitors","Prepare measurement connections","Build the first prioritised work order"].map(item=><div key={item} className="flex gap-3 text-sm"><CircleDot size={16} className="mt-0.5 shrink-0 text-[var(--flight-orange)]"/><span>{item}</span></div>)}</div><p className="mt-5 text-xs leading-5 text-[var(--muted)]">This starting plan uses only the details you supplied. Example routes remain labelled until real evidence exists.</p></Card></div><div className="mx-auto mt-7 flex max-w-4xl items-center justify-between"><Button variant="ghost" onClick={back}>Back</Button><Button size="lg" onClick={finish}>Open Flight Deck</Button></div></>
}
