"use client";
import { useState } from "react";
import { Card, Input } from "@/components/ui";
import { OnboardingNavigation } from "@/components/onboarding/onboarding-navigation";
import { StepIntro } from "@/components/onboarding/onboarding-shell";
import { normaliseWebsite, websiteSchema } from "@/lib/onboarding/schema";
import type { OnboardingData } from "@/lib/onboarding/types";

export function WebsiteStep({data,update,next}:{data:OnboardingData;update:(patch:Partial<OnboardingData>)=>void;next:()=>void}){
  const [values,setValues]=useState({websiteUrl:data.websiteUrl,businessName:data.businessName,location:data.location,crawlAuthorised:data.crawlAuthorised});const [errors,setErrors]=useState<Record<string,string>>({});
  function submit(event:React.FormEvent){event.preventDefault();const result=websiteSchema.safeParse(values);if(!result.success||!values.crawlAuthorised){setErrors({...Object.fromEntries(result.success?[]:result.error.issues.map(issue=>[String(issue.path[0]),issue.message])),crawlAuthorised:values.crawlAuthorised?"":"Confirm that you are authorised to analyse this website."});return}update({...result.data,websiteUrl:normaliseWebsite(result.data.websiteUrl),crawlAuthorised:true});next()}
  return <form onSubmit={submit}><StepIntro eyebrow="Let’s begin" title="What website do you want to grow?" description="We will request public HTML pages at a low rate and prepare an initial website overview."/><Card className="mx-auto max-w-3xl p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Input label="Website URL" placeholder="screenfizz.com" autoComplete="url" value={values.websiteUrl} onChange={event=>{setValues({...values,websiteUrl:event.target.value});setErrors({...errors,websiteUrl:""})}} error={errors.websiteUrl} hint="We’ll add https:// when it is omitted." required/></div><Input label="Business name" placeholder="Screenfizz" autoComplete="organization" value={values.businessName} onChange={event=>{setValues({...values,businessName:event.target.value});setErrors({...errors,businessName:""})}} error={errors.businessName} required/><Input label="Main business location (optional)" placeholder="Bristol, UK" value={values.location} onChange={event=>setValues({...values,location:event.target.value})}/><label className="sm:col-span-2 flex cursor-pointer gap-3 rounded-xl border border-[var(--border)] bg-[#f7f7f3] p-4 text-sm leading-6"><input type="checkbox" checked={values.crawlAuthorised} onChange={event=>{setValues({...values,crawlAuthorised:event.target.checked});setErrors({...errors,crawlAuthorised:""})}} className="mt-1 accent-[var(--accent)]"/><span>I am authorised to analyse this website and understand that the crawler will request publicly accessible pages at a low rate.{errors.crawlAuthorised&&<span className="mt-1 block text-[var(--error)]">{errors.crawlAuthorised}</span>}</span></label></div></Card><OnboardingNavigation nextType="submit" nextLabel="Analyse website"/></form>
}
