import { NextResponse } from "next/server";
import { z } from "zod";
import { crawlerLabOfflineAfterSeconds, getCrawlerLabContext } from "@/lib/crawler-lab/server";
const schema = z.discriminatedUnion("action", [z.object({ action: z.literal("run"), provider: z.enum(["native", "siteone"]) }), z.object({ action: z.literal("both") }), z.object({ action: z.literal("review"), groupId: z.string().uuid(), review: z.enum(["native_more_accurate", "siteone_more_accurate", "both_similar", "needs_investigation"]), notes: z.string().max(4000).optional() }), z.object({ action: z.literal("promote"), groupId: z.string().uuid(), crawlRunId: z.string().uuid() })]);
export async function POST(request: Request) {
  const input = schema.safeParse(await request.json().catch(() => null)); if (!input.success) return NextResponse.json({ error: "Invalid request." }, { status: 400 });
  const context = await getCrawlerLabContext(); if (!context) return NextResponse.json({ error: "Not found." }, { status: 404 });
  const { client, website } = context; const stale = crawlerLabOfflineAfterSeconds();
  const call = input.data.action === "both" ? client.rpc("create_crawler_comparison", { target_website_id: website.id, stale_after_seconds: stale }) : input.data.action === "run" ? client.rpc("start_crawler_lab_run", { target_website_id: website.id, selected_provider: input.data.provider, stale_after_seconds: stale }) : input.data.action === "review" ? client.rpc("review_crawler_comparison", { target_group_id: input.data.groupId, review: input.data.review, notes: input.data.notes || null }) : client.rpc("promote_crawl_run", { target_group_id: input.data.groupId, target_run_id: input.data.crawlRunId });
  const { data, error } = await call; if (error) return NextResponse.json({ error: safeError(error.message) }, { status: 400 }); return NextResponse.json({ data }, { headers: { "Cache-Control": "private, no-store" } });
}
function safeError(message: string) { const map: Record<string, string> = { native_worker_unavailable: "Native crawler is currently offline.", siteone_worker_unavailable: "SiteOne worker is currently offline.", siteone_project_not_allowed: "This project is not approved for internal SiteOne testing.", crawl_already_active: "An active crawl already exists for this provider.", crawl_not_promotable: "Only completed usable crawl results can be promoted.", crawl_has_no_usable_pages: "This crawl has no usable HTML pages to promote." }; return Object.entries(map).find(([key]) => message.includes(key))?.[1] || "Crawler Lab action could not be completed."; }
