"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2 } from "lucide-react";
import { z } from "zod";
import { Button, Input } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import { getAppUrl, isDemoMode } from "@/lib/config/env";
export default function ForgotPasswordPage(){const [email,setEmail]=useState("");const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(event:React.FormEvent){event.preventDefault();setError("");if(!z.string().email().safeParse(email).success){setError("Enter a valid email address.");return}if(isDemoMode()){setSent(true);return}const supabase=createClient();if(!supabase){setError("Password recovery is not configured yet.");return}setBusy(true);await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${getAppUrl()}/auth/callback?next=/update-password`});setBusy(false);setSent(true)}return <main className="grid min-h-screen place-items-center px-5"><div className="w-full max-w-md rounded-3xl border border-[var(--border)] bg-[var(--card)] p-7 shadow-sm"><Link href="/login" className="focus-ring mb-7 inline-flex items-center gap-2 rounded-lg text-sm text-[var(--muted)]"><ArrowLeft size={16}/>Back to login</Link>{sent?<div role="status" className="text-center"><CheckCircle2 className="mx-auto text-[var(--success)]" size={42}/><h1 className="mt-4 text-2xl font-semibold">Check your inbox</h1><p className="mt-2 text-[var(--muted)]">If an account can receive recovery email, a secure link is on its way. The message is intentionally generic.</p></div>:<><h1 className="text-2xl font-semibold">Reset your password</h1><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Enter your account email and we’ll send a secure recovery link.</p><form onSubmit={submit} className="mt-6 space-y-4"><Input label="Email address" type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} error={error} required/><Button size="lg" className="w-full" loading={busy}>Send recovery link</Button></form></>}</div></main>}
