"use client";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { AlertCircle, Compass } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { productConfig } from "@/lib/config/product";
import { Button, Input } from "@/components/ui";

export function AuthForm({mode}:{mode:"login"|"signup"}){
  const router=useRouter(); const params=useSearchParams();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const supabase=createClient(); const demo=!supabase;
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");
    try{
      if(demo){document.cookie="northstar-demo-session=1; path=/; max-age=2592000; samesite=lax";localStorage.setItem("northstar-demo-user",JSON.stringify({email,name:name||email.split("@")[0]}));router.push(mode==="signup"?"/onboarding":params.get("next")||"/app");router.refresh();return;}
      if(mode==="signup"){
        const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:`${location.origin}/auth/callback`}}); if(error)throw error; router.push("/onboarding");router.refresh();
      } else { const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;router.push(params.get("next")||"/app");router.refresh(); }
    }catch(err){setError(err instanceof Error?err.message:"Something went wrong. Please try again.");}finally{setBusy(false)}
  }
  async function google(){setBusy(true);setError(""); if(demo){document.cookie="northstar-demo-session=1; path=/; max-age=2592000; samesite=lax";router.push("/onboarding");router.refresh();return;} const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/auth/callback`}});if(error){setError(error.message);setBusy(false)}}
  return <div className="grid min-h-screen lg:grid-cols-2"><section className="flex items-center justify-center px-5 py-12"><div className="w-full max-w-md"><Link href="/" className="mb-10 inline-flex items-center gap-2 font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--accent)] text-white"><Compass size={19}/></span>{productConfig.name}</Link><h1 className="text-3xl font-semibold tracking-tight">{mode==="login"?"Welcome back":"Meet your SEO employee"}</h1><p className="mt-2 text-[var(--muted)]">{mode==="login"?"Continue where your organic growth plan left off.":"Create your workspace and get a practical first plan."}</p>{demo&&<div className="mt-5 rounded-xl border border-[#e6d6b7] bg-[#fcf2df] px-3.5 py-3 text-sm text-[#765020]"><strong>Demo mode:</strong> authentication and project data stay in this browser until Supabase is configured.</div>}
    <form onSubmit={submit} className="mt-7 space-y-4">{mode==="signup"&&<Input label="Your name" value={name} onChange={e=>setName(e.target.value)} required placeholder="Alex Morgan"/>}<Input label="Email address" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@company.com"/><Input label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} placeholder="At least 6 characters"/>{error&&<div role="alert" className="flex gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-700"><AlertCircle size={18}/>{error}</div>}<Button size="lg" className="w-full" loading={busy}>{mode==="login"?"Log in":"Create workspace"}</Button></form>
    <div className="my-5 flex items-center gap-3 text-xs text-[var(--muted)]"><span className="h-px flex-1 bg-[var(--line)]"/>OR<span className="h-px flex-1 bg-[var(--line)]"/></div><Button type="button" variant="secondary" size="lg" className="w-full" onClick={google} disabled={busy}><span className="font-bold text-[#4285f4]">G</span> Continue with Google</Button>
    <p className="mt-6 text-center text-sm text-[var(--muted)]">{mode==="login"?<>New to {productConfig.name}? <Link className="font-semibold text-[var(--accent)]" href="/signup">Create an account</Link></>:<>Already have an account? <Link className="font-semibold text-[var(--accent)]" href="/login">Log in</Link></>}</p>{mode==="login"&&<p className="mt-3 text-center text-sm"><Link href="/forgot-password" className="text-[var(--muted)] hover:text-[var(--ink)]">Forgot your password?</Link></p>}</div></section><aside className="soft-grid hidden border-l border-[var(--line)] bg-[#eef2ed] p-12 lg:flex lg:items-center"><div className="mx-auto max-w-lg"><p className="text-sm font-bold uppercase tracking-[.18em] text-[var(--accent)]">A focused first week</p><blockquote className="mt-5 text-4xl font-semibold leading-tight tracking-[-.04em]">Know what was learned, what is being worked on, and what happens next.</blockquote><div className="mt-10 grid gap-3">{["Understand your website and business","Prepare transparent opportunity hypotheses","Queue useful next steps without fake metrics"].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-2xl border border-white/70 bg-white/65 p-4"><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--accent)] text-sm font-bold text-white">{i+1}</span><span className="font-medium">{x}</span></div>)}</div></div></aside></div>
}
