"use client";

import { useState } from "react";
import Link from "next/link";
import { Compass, Info } from "lucide-react";
import { Button, Input } from "@/components/ui";
import { productConfig } from "@/lib/config/product";

export function AuthPlaceholder({ mode }: { mode: "login" | "signup" }) {
  const [notice, setNotice] = useState(false);
  return <main className="grid min-h-screen lg:grid-cols-2"><section className="flex items-center justify-center px-5 py-12"><div className="w-full max-w-md"><Link href="/" className="focus-ring mb-10 inline-flex items-center gap-2 rounded-lg font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--accent)] text-white"><Compass size={19}/></span>{productConfig.name}</Link><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--accent)]">Visual placeholder</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em]">{mode === "login" ? "Welcome back" : "Create your workspace"}</h1><p className="mt-2 leading-6 text-[var(--muted)]">Authentication is intentionally not connected in this foundation milestone.</p>{notice && <div role="status" className="mt-5 flex gap-2 rounded-xl border border-[#c8d8e6] bg-[#edf4fa] p-3 text-sm text-[#3e5a72]"><Info size={18}/><span>This form is a visual preview. Account access will be added in a later milestone.</span></div>}<form onSubmit={(event) => { event.preventDefault(); setNotice(true); }} className="mt-7 space-y-4">{mode === "signup" && <Input label="Your name" autoComplete="name" placeholder="Alex Morgan"/>}<Input label="Email address" type="email" autoComplete="email" placeholder="you@company.com" required/><Input label="Password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} placeholder="At least 8 characters" required minLength={8}/><Button size="lg" className="w-full">{mode === "login" ? "Preview login" : "Preview account setup"}</Button></form><p className="mt-6 text-center text-sm text-[var(--muted)]">{mode === "login" ? <>New here? <Link href="/signup" className="font-semibold text-[var(--accent)]">View signup</Link></> : <>Already have an account? <Link href="/login" className="font-semibold text-[var(--accent)]">View login</Link></>}</p>{mode === "login" && <p className="mt-3 text-center text-sm"><Link href="/forgot-password" className="text-[var(--muted)]">Forgot your password?</Link></p>}</div></section><aside className="soft-grid hidden border-l border-[var(--border)] bg-[#eef2ed] p-12 lg:flex lg:items-center"><div className="mx-auto max-w-lg"><p className="text-sm font-bold uppercase tracking-[.18em] text-[var(--accent)]">A calmer way to grow</p><p className="mt-5 text-4xl font-semibold leading-tight tracking-[-.04em]">Know what was discovered, what is happening, and what comes next.</p></div></aside></main>;
}
