"use client";
import { useState } from "react";
import { ChevronDown, ChevronUp, RotateCcw, Sparkles, X } from "lucide-react";
import { Badge, Button, Card, EmptyState } from "@/components/ui";
import { useProject } from "@/components/project-provider";
import type { Opportunity, OpportunityStatus } from "@/lib/types";

export function OpportunityList({items,contentMode=false}:{items:Opportunity[];contentMode?:boolean}){const {project,update}=useProject();const [open,setOpen]=useState<string|null>(null);function status(id:string,status:OpportunityStatus){update({opportunities:project.opportunities.map(o=>o.id===id?{...o,status}:o)})}if(!items.length)return <EmptyState icon={<Sparkles size={20}/>} title={contentMode?"No content hypotheses yet":"No opportunities here"} description={contentMode?"Once your business profile is complete, useful content starting points will appear here.":"New findings will appear here with a clear source and explanation."}/>;return <div className="space-y-3">{items.map(o=><Card key={o.id} className={`overflow-hidden ${o.status==="Dismissed"?"opacity-65":""}`}><button onClick={()=>setOpen(open===o.id?null:o.id)} className="flex w-full items-start gap-4 p-5 text-left"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><Badge tone="green">{contentMode?"Hypothesis":o.category}</Badge><Badge>{o.status}</Badge>{o.requiresRealData&&<Badge tone="blue">Needs data connection</Badge>}</div><h3 className="mt-3 font-semibold">{o.title}</h3><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{o.description}</p></div>{open===o.id?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>{open===o.id&&<div className="border-t border-[var(--line)] bg-[#f7f6f1] p-5"><div className="grid gap-4 sm:grid-cols-3"><Detail label="Why it matters" value={o.why}/><Detail label="Expected impact" value={o.impact}/><Detail label="Effort & confidence" value={`${o.effort} effort · ${o.confidence}`}/></div><p className="mt-4 text-xs text-[var(--muted)]">Source: {o.source} · No fake search volume or ranking data used.</p><div className="mt-5 flex flex-wrap gap-2">{o.status==="Dismissed"?<Button size="sm" variant="secondary" onClick={()=>status(o.id,"New")}><RotateCcw size={15}/> Restore</Button>:<><Button size="sm" onClick={()=>status(o.id,"Planned")}>Add to plan</Button><Button size="sm" variant="ghost" onClick={()=>status(o.id,"Dismissed")}><X size={15}/> Dismiss</Button></>}</div></div>}</Card>)}</div>}
function Detail({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">{label}</p><p className="mt-1 text-sm leading-6">{value}</p></div>}
