import * as React from "react";
import Link from "next/link";
import { LoaderCircle } from "lucide-react";
import { cn } from "@/lib/utils";

export function Button({ className, variant="primary", size="md", loading, children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary"|"secondary"|"ghost"|"danger"; size?: "sm"|"md"|"lg"; loading?: boolean }) {
  return <button className={cn("focus-ring inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition disabled:cursor-not-allowed disabled:opacity-50", size==="sm"?"px-3 py-2 text-sm":size==="lg"?"px-5 py-3.5":"px-4 py-2.5 text-sm", variant==="primary"&&"bg-[var(--accent)] text-white shadow-sm hover:bg-[var(--accent-strong)]",variant==="secondary"&&"border border-[var(--line)] bg-white hover:bg-[#f5f4ef]",variant==="ghost"&&"hover:bg-black/5",variant==="danger"&&"bg-red-50 text-red-700 hover:bg-red-100",className)} disabled={loading||props.disabled} {...props}>{loading&&<LoaderCircle size={16} className="animate-spin"/>}{children}</button>;
}
export function LinkButton({ href, children, variant="primary", className }: { href:string; children:React.ReactNode; variant?:"primary"|"secondary"|"ghost"; className?:string }) {
  return <Link href={href} className={cn("focus-ring inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition",variant==="primary"&&"bg-[var(--accent)] text-white shadow-sm hover:bg-[var(--accent-strong)]",variant==="secondary"&&"border border-[var(--line)] bg-white hover:bg-[#f5f4ef]",variant==="ghost"&&"hover:bg-black/5",className)}>{children}</Link>;
}
export function Card({ className, children }: { className?:string; children:React.ReactNode }) { return <div className={cn("rounded-2xl border border-[var(--line)] bg-[var(--surface)] shadow-[0_1px_2px_rgba(30,41,37,.035)]",className)}>{children}</div>; }
export function Badge({ children, tone="neutral" }: {children:React.ReactNode;tone?:"neutral"|"green"|"amber"|"blue"|"red"}) { return <span className={cn("inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold",tone==="neutral"&&"bg-[#eeeee9] text-[#646963]",tone==="green"&&"bg-[#e0eee7] text-[#28624f]",tone==="amber"&&"bg-[#faead7] text-[#8b551d]",tone==="blue"&&"bg-[#e5ecf5] text-[#466382]",tone==="red"&&"bg-red-50 text-red-700")}>{children}</span>; }
export function Input({ label, hint, error, className, ...props }: React.InputHTMLAttributes<HTMLInputElement> & {label?:string;hint?:string;error?:string}) { return <label className="block"><span className="mb-1.5 block text-sm font-semibold">{label}</span><input className={cn("focus-ring w-full rounded-xl border border-[var(--line)] bg-white px-3.5 py-3 text-[15px] placeholder:text-[#9a9f9c]",error&&"border-red-400",className)} {...props}/>{error?<span className="mt-1 block text-sm text-red-600">{error}</span>:hint&&<span className="mt-1 block text-xs text-[var(--muted)]">{hint}</span>}</label>; }
export function Textarea({ label, hint, className, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>&{label?:string;hint?:string}) { return <label className="block"><span className="mb-1.5 block text-sm font-semibold">{label}</span><textarea className={cn("focus-ring min-h-24 w-full resize-y rounded-xl border border-[var(--line)] bg-white px-3.5 py-3 text-[15px]",className)} {...props}/>{hint&&<span className="mt-1 block text-xs text-[var(--muted)]">{hint}</span>}</label>; }
export function Select({ label, children, className, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>&{label?:string}) { return <label className="block"><span className="mb-1.5 block text-sm font-semibold">{label}</span><select className={cn("focus-ring w-full rounded-xl border border-[var(--line)] bg-white px-3.5 py-3 text-[15px]",className)} {...props}>{children}</select></label>; }
export function EmptyState({ icon, title, description, action }: {icon?:React.ReactNode;title:string;description:string;action?:React.ReactNode}) { return <div className="flex flex-col items-center rounded-2xl border border-dashed border-[var(--line)] px-6 py-10 text-center">{icon&&<div className="mb-3 rounded-full bg-[var(--accent-soft)] p-3 text-[var(--accent)]">{icon}</div>}<h3 className="font-semibold">{title}</h3><p className="mt-1 max-w-md text-sm leading-6 text-[var(--muted)]">{description}</p>{action&&<div className="mt-4">{action}</div>}</div>; }
export function PageHeader({ eyebrow, title, description, action }: {eyebrow?:string;title:string;description?:string;action?:React.ReactNode}) { return <header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow&&<p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-[var(--accent)]">{eyebrow}</p>}<h1 className="text-2xl font-semibold tracking-[-.025em] sm:text-3xl">{title}</h1>{description&&<p className="mt-2 max-w-2xl leading-6 text-[var(--muted)]">{description}</p>}</div>{action}</header>; }
