import Link from "next/link";
import { ArrowRight, CheckCircle2, Route } from "lucide-react";
import { FlightBrand } from "@/components/flight/flight-deck";

export type InfoSection = { title: string; copy: string; points?: string[] };

export function MarketingInfoPage({ eyebrow, title, introduction, sections }: { eyebrow: string; title: string; introduction: string; sections: InfoSection[] }) {
  return <main className="min-h-screen bg-[var(--flight-bg)] text-[var(--flight-ink)]">
    <header className="border-b border-[var(--flight-border)] bg-[var(--flight-bg)]/95"><nav className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="focus-ring rounded-full"><FlightBrand /></Link><div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-xl px-4 py-3 text-sm font-semibold sm:inline-flex">Log in</Link><Link href="/onboarding" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[var(--flight-ink)] px-5 text-sm font-semibold text-white">Start pre-flight <ArrowRight size={15}/></Link></div></nav></header>
    <section className="flight-grid border-b border-[var(--flight-border)]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><p className="font-mono text-[10px] font-bold tracking-[.18em] text-[var(--flight-blue)]">{eyebrow}</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold tracking-[-.065em] sm:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--flight-muted)]">{introduction}</p><div className="mt-10 inline-flex items-center gap-3 rounded-full border border-[var(--flight-border)] bg-[var(--flight-surface)] px-4 py-2 font-mono text-[9px] font-bold tracking-[.13em] text-[var(--flight-muted)]"><Route size={14} className="text-[var(--flight-orange)]"/>SEARCHHAND FLIGHT PLAN</div></div></section>
    <section className="mx-auto grid max-w-7xl gap-4 px-5 py-20 md:grid-cols-2 lg:px-8 lg:py-28">{sections.map((section, index) => <article key={section.title} className={`rounded-[26px] border p-6 sm:p-8 ${index === 0 ? "border-[var(--flight-orange)] bg-[#fff5ef]" : "border-[var(--flight-border)] bg-[var(--flight-surface)]"}`}><span className="font-mono text-[9px] font-bold tracking-[.14em] text-[var(--flight-muted)]">ROUTE {String(index + 1).padStart(2, "0")}</span><h2 className="mt-5 text-2xl font-semibold tracking-[-.035em]">{section.title}</h2><p className="mt-3 leading-7 text-[var(--flight-muted)]">{section.copy}</p>{section.points && <div className="mt-6 space-y-3">{section.points.map((point) => <p key={point} className="flex items-start gap-3 text-sm"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-[var(--flight-green)]"/>{point}</p>)}</div>}</article>)}</section>
    <section className="mx-3 mb-3 rounded-[30px] bg-[var(--flight-night)] px-5 py-20 text-center text-white"><h2 className="mx-auto max-w-3xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">Set the destination.<br/><span className="text-white/35">We’ll handle the route.</span></h2><Link href="/onboarding" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-[var(--flight-orange)] px-6 text-sm font-semibold">Start pre-flight check <ArrowRight size={16}/></Link></section>
    <footer className="mx-auto flex max-w-7xl items-center justify-between px-5 py-10 lg:px-8"><FlightBrand/><Link href="/" className="text-sm font-semibold text-[var(--flight-muted)]">Back to homepage</Link></footer>
  </main>;
}
