"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import {
  ArrowRight, BarChart3, Check, CheckCircle2, ChevronDown,
  Circle, FilePenLine, Globe2, Layers3,
  Menu, MousePointerClick, PackageCheck, ScanSearch, ShieldCheck,
  Sparkles, Store, X, Zap,
} from "lucide-react";

const handling = [
  [ScanSearch, "Website inspection", "Checks your pages, links, titles and search accessibility."],
  [Sparkles, "Opportunity finding", "Finds the work most likely to make a useful difference."],
  [FilePenLine, "Page improvements", "Prepares clear updates to useful pages you already have."],
  [Layers3, "Content planning", "Plans new pages only when there is a genuine gap."],
  [ShieldCheck, "Quality checking", "Checks every change for accuracy, overlap and broken links."],
  [BarChart3, "Performance tracking", "Connects completed work to visibility, visits and enquiries."],
] as const;

const workflow = [
  ["01", "Inspect", "Maps your website and checks how search engines can understand it."],
  ["02", "Decide", "Chooses whether to fix, update, create, merge, link or ignore."],
  ["03", "Prepare", "Creates a clear work order and prepares the proposed changes."],
  ["04", "Verify", "Checks links, duplication, structure and business claims."],
  ["05", "Approve", "Shows exactly what changed before anything is published."],
  ["06", "Measure", "Checks whether completed work improved meaningful results."],
] as const;

const choices = [
  ["Fix", "Resolve a problem blocking an existing page."],
  ["Update", "Improve a page already receiving search visibility."],
  ["Create", "Build a new page when there is a genuine gap."],
  ["Merge", "Combine pages competing for the same search."],
  ["Link", "Strengthen useful pages with better connections."],
  ["Ignore", "Avoid low-value work that would create clutter."],
] as const;

const faqs = [
  ["Do I need to understand SEO?", "No. SEObot explains each job in plain language, why it matters and what it intends to change."],
  ["Will SEObot change my website without permission?", "No. The current workflow prepares work and waits for your approval. Nothing publishes automatically."],
  ["Is this another AI article generator?", "No. It improves useful existing pages first and only recommends new content when evidence shows a genuine gap."],
  ["What website platforms are supported?", "Public website inspection works independently of your platform. Publishing connections are being developed and are always labelled honestly."],
  ["How long does SEO take?", "It varies by market, website and search engine. SEObot makes the work visible, but does not promise a ranking or a deadline."],
  ["Can SEObot improve existing pages?", "Yes. Updating pages that already show signs of demand is a central part of how SEObot prioritises work."],
  ["Can it work with a local business?", "Yes. It can focus on service pages, locations and the information nearby customers need before contacting you."],
  ["What happens if I cancel?", "Your website remains yours. Completed work stays on your site, and connections can be revoked."],
  ["Does it guarantee rankings?", "No responsible SEO product can guarantee rankings. SEObot focuses on useful, reviewable improvements and transparent evidence."],
  ["Is my website data safe?", "Inspection begins with public pages only. Private access and publishing permissions are separate, explicit connections you control."],
] as const;

function Brand({ inverse = false }: { inverse?: boolean }) {
  return <span className={`inline-flex items-center gap-2 font-bold tracking-[-.03em] ${inverse ? "text-white" : "text-[#171717]"}`}><span className="relative grid h-8 w-8 place-items-center overflow-hidden rounded-lg bg-[#f26a2e] text-white"><span className="absolute inset-y-0 left-1/2 w-px bg-white/30"/><span className="absolute inset-x-0 top-1/2 h-px bg-white/30"/><Sparkles size={15}/></span>SEObot</span>;
}

function UrlForm({ dark = false }: { dark?: boolean }) {
  const router = useRouter();
  const [url, setUrl] = useState("");
  function submit(event: FormEvent) {
    event.preventDefault();
    const clean = url.trim();
    const destination = clean ? `/onboarding?website=${encodeURIComponent(clean)}` : "/onboarding";
    router.push(`/signup?next=${encodeURIComponent(destination)}`);
  }
  return <form onSubmit={submit} className={`flex w-full max-w-[590px] flex-col gap-2 rounded-2xl border p-2 shadow-sm sm:flex-row ${dark ? "border-white/15 bg-white/10" : "border-[#dedad1] bg-white"}`}>
    <label className="sr-only" htmlFor={dark ? "final-url" : "hero-url"}>Website URL</label>
    <div className="flex min-w-0 flex-1 items-center gap-2 px-2"><Globe2 size={17} className={dark ? "text-white/50" : "text-[#8a857d]"}/><input id={dark ? "final-url" : "hero-url"} value={url} onChange={e => setUrl(e.target.value)} placeholder="yourwebsite.com" className={`w-full bg-transparent py-2.5 text-[15px] outline-none ${dark ? "text-white placeholder:text-white/40" : "text-[#171717] placeholder:text-[#9b968e]"}`}/></div>
    <button className="focus-ring inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-[#f26a2e] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#d95620]">Inspect my website <ArrowRight size={16}/></button>
  </form>;
}

function WorkshopPreview() {
  const stages = ["Inspecting", "Deciding", "Preparing", "Verifying"];
  const [stage, setStage] = useState(0);
  useEffect(() => { const id = window.setInterval(() => setStage(v => (v + 1) % 4), 3000); return () => window.clearInterval(id); }, []);
  return <div className="workshop-shadow relative overflow-hidden rounded-[26px] border border-[#d8d3ca] bg-[#fffefb]">
    <div className="flex items-center justify-between border-b border-[#dedad1] bg-[#faf8f3] px-5 py-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-[#f26a2e]"/><span className="font-mono text-[11px] font-bold tracking-[.16em]">SEOBOT WORKSHOP</span></div><span className="flex items-center gap-1.5 font-mono text-[10px] font-bold text-[#2f9d68]"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#2f9d68]"/>ACTIVE</span></div>
    <div className="grid sm:grid-cols-[150px_1fr]">
      <div className="hidden border-r border-[#dedad1] bg-[#faf8f3] p-4 sm:block"><p className="font-mono text-[9px] font-bold tracking-[.15em] text-[#8a857d]">STAGES</p><div className="mt-4 space-y-4">{stages.map((item, index) => <div key={item} className={`flex items-center gap-2 text-xs font-semibold transition ${index === stage ? "text-[#171717]" : index < stage ? "text-[#2f9d68]" : "text-[#a6a19a]"}`}><span className={`grid h-5 w-5 place-items-center rounded-full border text-[9px] ${index < stage ? "border-[#2f9d68] bg-[#e9f6ef]" : index === stage ? "border-[#f26a2e] bg-[#fff0e8]" : "border-[#dedad1]"}`}>{index < stage ? <Check size={11}/> : index + 1}</span>{item}</div>)}</div></div>
      <div className="relative min-h-[430px] p-5 sm:p-6"><div className="scan-line pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#6d5dfb] to-transparent"/>
        <div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[9px] font-bold tracking-[.15em] text-[#8a857d]">WEBSITE</p><p className="mt-1 font-mono text-xs">screenfizz.com</p></div><span className="rounded-full bg-[#efedff] px-2.5 py-1 font-mono text-[9px] font-bold text-[#5c4ce0]">{stages[stage].toUpperCase()}</span></div>
        <div className="mt-6 rounded-2xl border border-[#dedad1] p-4"><p className="font-mono text-[9px] font-bold tracking-[.15em] text-[#8a857d]">INSPECTION</p><div className="mt-3 grid gap-2 text-xs">{["34 pages mapped", "Technical health checked", "Existing content understood"].map(item => <span key={item} className="flex items-center gap-2"><CheckCircle2 size={15} className="text-[#2f9d68]"/>{item}</span>)}</div></div>
        <div className="mt-3 rounded-2xl bg-[#171717] p-4 text-white"><div className="flex items-center justify-between"><p className="font-mono text-[9px] font-bold tracking-[.15em] text-white/50">WORK ORDER #018</p><span className="h-2 w-2 rounded-full bg-[#f26a2e]"/></div><p className="mt-3 text-sm font-semibold">Improve the managed signage pricing page</p><p className="mt-2 text-xs leading-5 text-white/55">Selected because this page already appears in search but ranks just outside the first page.</p></div>
        <div className={`mt-3 grid gap-2 transition-opacity duration-500 ${stage >= 2 ? "opacity-100" : "opacity-45"}`}><div className="rounded-lg bg-[#fff0f0] px-3 py-2 font-mono text-[10px] text-[#a83f3f] line-through">Digital Signage Pricing</div><div className="rounded-lg bg-[#e9f6ef] px-3 py-2 font-mono text-[10px] text-[#237a50]">Managed Digital Signage Pricing for UK Businesses</div></div>
        <div className={`mt-3 flex items-center gap-2 text-xs font-semibold transition ${stage === 3 ? "text-[#2f9d68]" : "text-[#8a857d]"}`}><PackageCheck size={16}/>{stage === 3 ? "VERIFIED · Ready for approval" : "Preparing reviewable changes"}</div>
      </div>
    </div>
  </div>;
}

function Tour() {
  const tabs = {
    Website: { icon: Globe2, eyebrow: "WEBSITE INSPECTION", title: "A clear map of what is working", copy: "34 public pages inspected · 3 important issues", rows: [["Pages available", "32"], ["Broken pages", "2"], ["Important issues", "3"]] },
    Opportunities: { icon: Sparkles, eyebrow: "RECOMMENDED WORK", title: "Improve your pricing page", copy: "Strong existing demand · High confidence", rows: [["Impact", "High"], ["Evidence", "Search visibility"], ["Decision", "Update"]] },
    Changes: { icon: FilePenLine, eyebrow: "PROPOSED CHANGE", title: "Make the offer clearer", copy: "A simple explanation sits beside every detailed diff.", rows: [["Title update", "Ready"], ["Internal links", "+3"], ["Business claims", "Verified"]] },
    Results: { icon: BarChart3, eyebrow: "AFTER PUBLISHING", title: "See what happened next", copy: "Measure completed work without claiming credit for every change.", rows: [["Impressions", "310 → 720"], ["Clicks", "9 → 34"], ["Position", "14.2 → 8.7"]] },
  } as const;
  const [active, setActive] = useState<keyof typeof tabs>("Website");
  const item = tabs[active]; const Icon = item.icon;
  return <div><div className="mx-auto flex max-w-xl overflow-x-auto rounded-xl border border-[#dedad1] bg-[#eeeae3] p-1">{Object.keys(tabs).map(tab => <button key={tab} onClick={() => setActive(tab as keyof typeof tabs)} className={`min-w-max flex-1 rounded-lg px-4 py-2.5 text-sm font-semibold transition ${active === tab ? "bg-white text-[#171717] shadow-sm" : "text-[#68645d]"}`}>{tab}</button>)}</div><div className="blueprint-grid workshop-shadow mx-auto mt-7 max-w-4xl rounded-[28px] border border-[#dedad1] bg-[#fffefb] p-5 sm:p-8"><div className="grid gap-7 md:grid-cols-[1fr_.8fr] md:items-center"><div><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#efedff] text-[#6d5dfb]"><Icon size={21}/></span><p className="mt-8 font-mono text-[10px] font-bold tracking-[.17em] text-[#6d5dfb]">{item.eyebrow}</p><h3 className="mt-3 text-3xl font-semibold tracking-[-.04em]">{item.title}</h3><p className="mt-3 max-w-md leading-7 text-[#68645d]">{item.copy}</p></div><div className="rounded-2xl border border-[#dedad1] bg-white p-2 shadow-sm">{item.rows.map(([label, value]) => <div key={label} className="flex items-center justify-between border-b border-[#eeeae3] px-3 py-4 last:border-0"><span className="text-sm text-[#68645d]">{label}</span><span className="font-mono text-xs font-bold">{value}</span></div>)}</div></div></div></div>;
}

export function LandingPage() {
  const [menu, setMenu] = useState(false);
  return <main className="overflow-hidden bg-[#f7f5f0] text-[#171717]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-[#dedad1]/80 bg-[#f7f5f0]/90 backdrop-blur-xl"><nav className="mx-auto flex h-[70px] max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" aria-label="SEObot home"><Brand/></Link><div className="hidden items-center gap-7 text-sm font-medium text-[#68645d] md:flex"><a href="#how">How it works</a><a href="#features">Features</a><a href="#integrations">Integrations</a><a href="#pricing">Pricing</a><a href="#faq">Resources</a></div><div className="hidden items-center gap-2 md:flex"><Link href="/login" className="px-4 py-2.5 text-sm font-semibold">Log in</Link><Link href="/onboarding" className="rounded-xl bg-[#171717] px-4 py-2.5 text-sm font-semibold text-white">Inspect my website</Link></div><div className="flex items-center gap-2 md:hidden"><Link href="/onboarding" className="rounded-lg bg-[#f26a2e] px-3 py-2 text-xs font-semibold text-white">Start free</Link><button aria-label="Toggle menu" onClick={() => setMenu(v => !v)} className="grid h-9 w-9 place-items-center rounded-lg border border-[#dedad1] bg-white">{menu ? <X size={18}/> : <Menu size={18}/>}</button></div></nav>{menu && <div className="border-t border-[#dedad1] bg-[#fffefb] px-5 py-5 md:hidden"><div className="grid gap-4 text-sm font-semibold">{[["How it works", "#how"], ["Features", "#features"], ["Integrations", "#integrations"], ["Pricing", "#pricing"], ["Log in", "/login"]].map(([label, href]) => <a key={label} href={href} onClick={() => setMenu(false)}>{label}</a>)}</div></div>}</header>

    <section className="soft-grid border-b border-[#dedad1] pt-[70px]"><div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 lg:grid-cols-[1fr_.95fr] lg:items-center lg:px-8 lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#dedad1] bg-[#fffefb] px-3 py-1.5 font-mono text-[10px] font-bold tracking-[.15em] text-[#6d5dfb]"><span className="h-1.5 w-1.5 rounded-full bg-[#6d5dfb]"/>AUTONOMOUS SEO AGENT</div><h1 className="text-balance mt-7 max-w-2xl text-5xl font-semibold leading-[.98] tracking-[-.06em] sm:text-6xl lg:text-[72px]">Your SEO is being handled.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#68645d]">SEObot inspects your website, chooses the most valuable work, prepares improvements and shows you exactly what changed.</p><div className="mt-8"><UrlForm/></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#68645d]"><span className="flex items-center gap-1.5"><Check size={14} className="text-[#2f9d68]"/>No SEO experience needed</span><span className="flex items-center gap-1.5"><ShieldCheck size={14} className="text-[#2f9d68]"/>Nothing publishes without your approval</span></div><a href="#how" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold">See how it works <ArrowRight size={16}/></a></div><WorkshopPreview/></div></section>

    <section id="features" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#f26a2e]">WHAT SEOBOT HANDLES</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Useful work, from first look to final check.</h2></div><p className="max-w-md text-sm leading-6 text-[#68645d]">A complete SEO workflow, translated into decisions a business owner can understand.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-[#dedad1] bg-[#dedad1] sm:grid-cols-2 lg:grid-cols-3">{handling.map(([Icon,title,copy]) => <div key={title} className="bg-[#fffefb] p-6"><Icon size={20} className="text-[#f26a2e]"/><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#68645d]">{copy}</p></div>)}</div></section>

    <section className="bg-[#171717] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><div><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#f26a2e]">NOT ANOTHER SEO DASHBOARD</p><h2 className="text-balance mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Most SEO tools give you more data.<br/><span className="text-white/45">SEObot gives you work ready to review.</span></h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-xs font-semibold text-white/40">TRADITIONAL SEO SOFTWARE</p><div className="mt-5 space-y-3 text-sm text-white/60">{["143 warnings", "1,248 keywords", "17 charts", "A long report to understand"].map(item => <p key={item}>{item}</p>)}</div></div><div className="rounded-2xl bg-[#fffefb] p-5 text-[#171717]"><p className="font-mono text-[10px] font-bold text-[#f26a2e]">RECOMMENDED NEXT JOB</p><h3 className="mt-4 text-xl font-semibold">Improve your pricing page.</h3><p className="mt-3 text-sm leading-6 text-[#68645d]">It already receives search impressions and is close to the first page.</p><button className="mt-5 inline-flex items-center gap-2 text-sm font-semibold">Review the work plan <ArrowRight size={15}/></button></div></div></div></section>

    <section id="how" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="text-center"><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#6d5dfb]">INSPECT · IMPROVE · VERIFY · SHIP</p><h2 className="text-balance mx-auto mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">One agent. A visible process. You stay in control.</h2></div><div className="relative mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><div className="absolute left-0 right-0 top-7 hidden h-px bg-[#dedad1] lg:block"/>{workflow.map(([number,title,copy]) => <div key={number} className="relative rounded-2xl border border-[#dedad1] bg-[#fffefb] p-6"><span className="relative grid h-14 w-14 place-items-center rounded-full border border-[#dedad1] bg-[#f7f5f0] font-mono text-xs font-bold text-[#f26a2e]">{number}</span><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#68645d]">{copy}</p></div>)}</div></section>

    <section className="border-y border-[#dedad1] bg-[#fffefb]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#f26a2e]">CAREFUL BY DESIGN</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">Not every opportunity needs another article.</h2><p className="mt-5 leading-7 text-[#68645d]">SEObot chooses the right kind of work—and avoids busywork that wastes time or creates clutter.</p></div><div className="grid gap-3 sm:grid-cols-2">{choices.map(([title,copy], i) => <div key={title} className="group rounded-2xl border border-[#dedad1] p-5 transition hover:-translate-y-0.5 hover:border-[#f26a2e]"><div className="flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-lg font-mono text-[10px] font-bold ${i === 5 ? "bg-[#eeeae3]" : "bg-[#fff0e8] text-[#d95620]"}`}>{i+1}</span><h3 className="font-semibold">{title}</h3></div><p className="mt-3 text-sm leading-6 text-[#68645d]">{copy}</p></div>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="text-center"><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#6d5dfb]">INTERACTIVE PRODUCT TOUR</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">See the work. Not just the promise.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-[#68645d]">Every recommendation connects the evidence, the proposed change and what happened afterwards.</p></div><div className="mt-12"><Tour/></div></section>

    <section className="border-y border-[#dedad1] bg-[#eeeae3]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#f26a2e]">MADE FOR REAL BUSINESSES</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em]">Built for businesses that need customers, not SEO homework.</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[Store,"Local businesses","Improve service pages, local visibility and the details customers need before calling.","Improve the Bedford service page."],[Zap,"SaaS & apps","Turn product launches into useful pages that keep attracting the right users.","Compare our product to a genuine alternative."],[PackageCheck,"Ecommerce","Improve categories, discovery and buying-intent pages before adding more blogs.","Improve the collection page."],[Layers3,"Agencies","Review and approve work across multiple client websites in one clear history.","Prepare work for client approval."]].map(([Icon,title,copy,order]) => {const I=Icon as typeof Store; return <div key={title as string} className="rounded-2xl border border-[#d6d1c8] bg-[#fffefb] p-5"><I size={20} className="text-[#6d5dfb]"/><h3 className="mt-5 font-semibold">{title as string}</h3><p className="mt-2 min-h-20 text-sm leading-6 text-[#68645d]">{copy as string}</p><div className="mt-5 rounded-xl bg-[#f7f5f0] p-3 font-mono text-[10px] leading-5">{order as string}</div></div>})}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#6d5dfb]">APPROVAL & CONTROL</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">You decide how much control the agent has.</h2><p className="mt-5 leading-7 text-[#68645d]">Start with reviewable work. Your publishing permissions are explicit, visible and revocable.</p></div><div className="space-y-3">{[["Manual","SEObot finds opportunities. You choose which work begins.","Available"],["Assisted","SEObot prepares the work and waits for your approval.","Recommended"],["Autopilot","Approved repetitive work could be completed automatically.","Future"]].map(([title,copy,status],i) => <div key={title} className={`flex gap-4 rounded-2xl border p-5 ${i===1 ? "border-[#f26a2e] bg-[#fff0e8]" : "border-[#dedad1] bg-[#fffefb]"}`}><span className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full border ${i===1 ? "border-[#f26a2e] bg-[#f26a2e] text-white" : "border-[#c7c2b9]"}`}>{i===1 ? <Check size={14}/> : <Circle size={10}/>}</span><div className="flex-1"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{title}</h3><span className="font-mono text-[9px] font-bold tracking-[.12em] text-[#68645d]">{status.toUpperCase()}</span></div><p className="mt-1 text-sm leading-6 text-[#68645d]">{copy}</p></div></div>)}</div></div></section>

    <section id="integrations" className="bg-[#171717] text-white"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#f26a2e]">INTEGRATIONS</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">Works with the website you already have.</h2></div><p className="max-w-md text-sm leading-6 text-white/55">We label every connection honestly. Inspection is available now; publishing integrations are in development or planned.</p></div><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{[["WordPress","In development"],["Shopify","Planned"],["Webflow","Planned"],["Wix","Planned"],["Framer","Planned"],["Ghost","Planned"],["Webhook","Planned"],["API","Planned"],["Hosted Blog","Planned"]].map(([name,status]) => <div key={name} className="rounded-xl border border-white/10 bg-white/[.04] p-4"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/10 font-bold">{name[0]}</span><span className="text-sm font-semibold">{name}</span></div><p className={`mt-4 font-mono text-[9px] font-bold ${status==="In development" ? "text-[#f0b14b]" : "text-white/35"}`}>{status.toUpperCase()}</p></div>)}</div><div className="mt-8 flex flex-col justify-between gap-4 rounded-2xl border border-white/10 bg-white/[.06] p-6 sm:flex-row sm:items-center"><div><p className="font-semibold">Don’t see your website platform?</p><p className="mt-1 text-sm text-white/50">A hosted SEO-ready blog on <span className="font-mono text-white/75">blog.yourbusiness.com</span> is planned.</p></div><a href="#faq" className="inline-flex items-center gap-2 text-sm font-semibold">Explore integrations <ArrowRight size={16}/></a></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#2f9d68]">PRODUCT PROOF</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">Checked before it reaches you.</h2><p className="mt-4 leading-7 text-[#68645d]">No made-up testimonials. The proof is in a visible quality process for every work order.</p></div><div className="grid gap-3 sm:grid-cols-2">{["Search intent","Existing page overlap","Broken links","Unsupported claims","Internal linking","Metadata","Page accessibility","Business accuracy"].map(item => <div key={item} className="flex items-center gap-3 rounded-xl border border-[#dedad1] bg-[#fffefb] px-4 py-3.5 text-sm font-medium"><CheckCircle2 size={17} className="text-[#2f9d68]"/>{item}</div>)}</div></div></section>

    <section id="pricing" className="border-y border-[#dedad1] bg-[#fffefb]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="text-center"><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#f26a2e]">PLANS THAT GROW WITH THE WORK</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">Start with a free website inspection.</h2><p className="mx-auto mt-4 max-w-xl text-[#68645d]">Prices will be shown here once plans are confirmed. No invented numbers or confusing credit systems.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{[["Starter","For one small website.",["Website inspections","Prioritised opportunities","Work plans","Approval workflow"]],["Growth","For regular improvements.",["Everything in Starter","Content updates and briefs","Publishing integrations","Results tracking"]],["Agency","For multiple client websites.",["Multiple projects","Team approvals","Client work history","Higher usage"]]].map(([title,copy,features],i) => <div key={title as string} className={`rounded-2xl border p-6 ${i===1 ? "border-[#f26a2e] bg-[#fff8f3]" : "border-[#dedad1]"}`}><div className="flex items-center justify-between"><h3 className="text-xl font-semibold">{title as string}</h3>{i===1&&<span className="rounded-full bg-[#f26a2e] px-2.5 py-1 text-[10px] font-bold text-white">POPULAR</span>}</div><p className="mt-2 text-sm text-[#68645d]">{copy as string}</p><div className="my-6 h-px bg-[#dedad1]"/><div className="space-y-3">{(features as string[]).map(f => <p key={f} className="flex gap-2 text-sm"><Check size={16} className="text-[#2f9d68]"/>{f}</p>)}</div><Link href="/onboarding" className={`mt-8 flex items-center justify-center rounded-xl px-4 py-3 text-sm font-semibold ${i===1 ? "bg-[#f26a2e] text-white" : "border border-[#dedad1] bg-white"}`}>Start free inspection</Link></div>)}</div></div></section>

    <section id="faq" className="mx-auto max-w-4xl px-5 py-24"><div className="text-center"><p className="font-mono text-[10px] font-bold tracking-[.17em] text-[#6d5dfb]">STRAIGHT ANSWERS</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">Before you put the agent to work.</h2></div><div className="mt-10 divide-y divide-[#dedad1] border-y border-[#dedad1]">{faqs.map(([question,answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold"><span>{question}</span><ChevronDown size={18} className="shrink-0 transition group-open:rotate-180"/></summary><p className="mt-3 max-w-3xl pr-8 text-sm leading-6 text-[#68645d]">{answer}</p></details>)}</div></section>

    <section className="mx-3 mb-3 rounded-[28px] bg-[#171717] text-white sm:mx-5"><div className="soft-grid mx-auto flex max-w-5xl flex-col items-center px-5 py-20 text-center"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#f26a2e]"><MousePointerClick size={22}/></span><h2 className="text-balance mt-7 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Your website is already live.<br/><span className="text-white/45">Now give it an agent that keeps improving it.</span></h2><div className="mt-8 flex w-full justify-center"><UrlForm dark/></div><p className="mt-4 text-xs text-white/45">No SEO experience needed. Nothing publishes without your approval.</p></div></section>

    <footer className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-10 sm:flex-row sm:items-center sm:justify-between lg:px-8"><Brand/><p className="text-xs text-[#68645d]">Inspect. Improve. Verify. Ship.</p><div className="flex gap-5 text-xs font-semibold text-[#68645d]"><a href="#faq">FAQ</a><Link href="/login">Log in</Link><a href="#integrations">Integrations</a></div></footer>
  </main>;
}
