import "server-only";
import { getCurrentProject, getOptionalUser } from "@/lib/auth/server";
import { getComposioClient } from "@/lib/composio/client";
import { GOOGLE_ANALYTICS_LIST_ACCOUNT_SUMMARIES_ACTION, GOOGLE_ANALYTICS_TOOLKIT_VERSION } from "@/lib/composio/constants";
import { getComposioUserId } from "@/lib/composio/identity";
import { buildGoogleAnalyticsCallbackUrl, createCallbackState, verifyCallbackState } from "@/lib/composio/state";
import { getGoogleAnalyticsEnv } from "@/lib/config/publishing-env";
import { createPublishingAdminClient } from "@/lib/supabase/admin";

type ConnectionConfig={stateHash?:string;composioUserId?:string;connectedAccountId?:string;authConfigId?:string;properties?:Array<{name:string;displayName:string;accountName:string}>;property?:string};
type Summary={account?:string;displayName?:string;propertySummaries?:Array<{property?:string;displayName?:string}>};

async function context(){const[user,project]=await Promise.all([getOptionalUser(),getCurrentProject()]);if(!user||!project)throw new Error("authentication_required");return{user,project,admin:createPublishingAdminClient()}}
function config(value:unknown):ConnectionConfig{return value&&typeof value==="object"&&!Array.isArray(value)?value as ConnectionConfig:{}}
function properties(value:unknown){const summaries=((value&&typeof value==="object"&&(value as {accountSummaries?:unknown}).accountSummaries)||[]) as Summary[];return summaries.flatMap(summary=>(summary.propertySummaries||[]).flatMap(item=>item.property?[{name:item.property,displayName:item.displayName||item.property,accountName:summary.displayName||summary.account||"Google Analytics"}]:[]))}

export async function beginGoogleAnalyticsConnection(){const env=getGoogleAnalyticsEnv();if(!env)throw new Error("configuration_missing");const{user,project,admin}=await context();const state=createCallbackState();const composioUserId=getComposioUserId(user.id);const {error}=await admin.from("integrations").upsert({project_id:project.id,provider:"google_analytics",status:"not_connected",configuration:{stateHash:state.hash,composioUserId,authConfigId:env.COMPOSIO_GOOGLE_ANALYTICS_AUTH_CONFIG_ID}},{onConflict:"project_id,provider"});if(error)throw new Error("connection_save_failed");const linked=await getComposioClient().connectedAccounts.link(composioUserId,env.COMPOSIO_GOOGLE_ANALYTICS_AUTH_CONFIG_ID,{callbackUrl:buildGoogleAnalyticsCallbackUrl(env.APP_URL,state.value),alias:`searchhand-ga-${project.id.slice(0,8)}`,allowMultiple:false},{signal:AbortSignal.timeout(15_000)});if(!linked.redirectUrl)throw new Error("connection_link_failed");await admin.from("integrations").update({configuration:{stateHash:state.hash,composioUserId,authConfigId:env.COMPOSIO_GOOGLE_ANALYTICS_AUTH_CONFIG_ID,connectedAccountId:linked.id}}).eq("project_id",project.id).eq("provider","google_analytics");return linked.redirectUrl}

export async function completeGoogleAnalyticsConnection(state:string){const env=getGoogleAnalyticsEnv();if(!env)throw new Error("configuration_missing");const{project,admin}=await context();const{data:row}=await admin.from("integrations").select("configuration").eq("project_id",project.id).eq("provider","google_analytics").maybeSingle();const saved=config(row?.configuration);if(!saved.stateHash||!saved.connectedAccountId||!saved.composioUserId||!verifyCallbackState(state,saved.stateHash))throw new Error("invalid_callback");const accounts=await getComposioClient().connectedAccounts.list({userIds:[saved.composioUserId],authConfigIds:[env.COMPOSIO_GOOGLE_ANALYTICS_AUTH_CONFIG_ID],toolkitSlugs:["google_analytics"],limit:20},{signal:AbortSignal.timeout(15_000)});const account=accounts.items.find(item=>item.id===saved.connectedAccountId);if(!account||account.status.toLowerCase()!=="active")throw new Error("authorization_incomplete");const result=await getComposioClient().tools.execute(GOOGLE_ANALYTICS_LIST_ACCOUNT_SUMMARIES_ACTION,{userId:saved.composioUserId,connectedAccountId:saved.connectedAccountId,version:GOOGLE_ANALYTICS_TOOLKIT_VERSION,arguments:{pageSize:200}},{signal:AbortSignal.timeout(30_000)});if(!result.successful)throw new Error("property_lookup_failed");const found=properties(result.data);await admin.from("integrations").update({status:"connected",configuration:{...saved,stateHash:undefined,authConfigId:env.COMPOSIO_GOOGLE_ANALYTICS_AUTH_CONFIG_ID,properties:found},connected_at:new Date().toISOString(),last_synced_at:new Date().toISOString(),error_message:null}).eq("project_id",project.id).eq("provider","google_analytics");return found}

export async function readGoogleAnalyticsConnection(){const{project,admin}=await context();const{data}=await admin.from("integrations").select("status,configuration,connected_at,error_message").eq("project_id",project.id).eq("provider","google_analytics").maybeSingle();const saved=config(data?.configuration);return{status:data?.status||"not_connected",connectedAt:data?.connected_at||null,error:data?.error_message||null,property:saved.property||null,properties:saved.properties||[]}}
export async function selectGoogleAnalyticsProperty(property:string){const{project,admin}=await context();const{data}=await admin.from("integrations").select("configuration").eq("project_id",project.id).eq("provider","google_analytics").single();if(!data)throw new Error("connection_not_found");const saved=config(data.configuration);if(!saved.properties?.some(item=>item.name===property))throw new Error("invalid_property");await admin.from("integrations").update({configuration:{...saved,property}}).eq("project_id",project.id).eq("provider","google_analytics")}
export async function disconnectGoogleAnalytics(){const{project,admin}=await context();const{data}=await admin.from("integrations").select("configuration").eq("project_id",project.id).eq("provider","google_analytics").maybeSingle();const saved=config(data?.configuration);if(saved.connectedAccountId)await getComposioClient().connectedAccounts.delete(saved.connectedAccountId,{signal:AbortSignal.timeout(15_000)});await admin.from("integrations").update({status:"not_connected",configuration:{},error_message:null}).eq("project_id",project.id).eq("provider","google_analytics")}
