"use client";
import { useCallback,useEffect,useState } from "react";
import { Badge,Button,Card,EmptyState } from "@/components/ui";
type Property={siteUrl:string;permissionLevel:string};
type State={connection:{id:string;property_url:string|null;property_type:string|null;permission_level:string|null;status:string;last_successful_sync_at:string|null;last_error_message:string|null}|null;session:{id:string;properties:Property[];expiresAt:string}|null};
export function GscConnection({sessionId,errorCode}:{sessionId?:string;errorCode?:string}){
  const[state,setState]=useState<State|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState(errorCode?"Google did not complete the connection. Please try again.":"");
  const load=useCallback(async()=>{const response=await fetch(`/api/integrations/google-search-console${sessionId?`?session=${sessionId}`:""}`,{cache:"no-store"});if(response.ok)setState(await response.json())},[sessionId]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  async function select(propertyUrl:string){if(!state?.session)return;setBusy(true);const response=await fetch("/api/integrations/google-search-console/property",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:state.session.id,propertyUrl})});const payload=await response.json().catch(()=>({}));if(!response.ok)setError(payload.error||"The property could not be selected.");else window.location.assign("/app/integrations/google-search-console");setBusy(false)}
  async function disconnect(){setBusy(true);await fetch("/api/integrations/google-search-console",{method:"DELETE"});await load();setBusy(false)}
  if(!state)return<Card className="h-40 animate-pulse"><span className="sr-only">Loading connection</span></Card>;
  if(state.session)return<div className="space-y-4"><Card className="p-5"><h2 className="font-semibold">Choose the matching verified property</h2><p className="mt-2 text-sm text-[var(--flight-muted)]">A domain property covers all protocols and subdomains. A URL-prefix property covers only the exact prefix shown.</p></Card>{state.session.properties.map(property=><Card key={property.siteUrl} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="break-all font-semibold">{property.siteUrl}</p><p className="mt-1 text-xs text-[var(--flight-muted)]">{property.siteUrl.startsWith("sc-domain:")?"Domain property":"URL-prefix property"} · {property.permissionLevel}</p></div><Button disabled={busy} onClick={()=>select(property.siteUrl)}>Use this property</Button></Card>)}{state.session.properties.length===0&&<EmptyState title="No usable verified properties found" description="Ask a Search Console owner to grant this Google account access, then reconnect."/>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div>;
  if(!state.connection||state.connection.status==="disconnected")return<EmptyState title="Google Search Console is not connected" description="Connect securely through Composio to see which searches show your website and where Searchhand can improve results." action={<><a href="/api/integrations/google-search-console/connect" className="inline-flex rounded-xl bg-[var(--flight-ink)] px-4 py-3 text-sm font-semibold text-white">Connect Google Search Console</a>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</>}/>;
  return<Card className="p-5"><div className="flex flex-col gap-5 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><Badge tone={state.connection.status==="connected"?"green":state.connection.status==="needs_reauthentication"||state.connection.status==="error"?"red":"amber"}>{state.connection.status.replaceAll("_"," ")}</Badge><h2 className="mt-3 break-all font-semibold">{state.connection.property_url}</h2><p className="mt-2 text-sm text-[var(--flight-muted)]">{state.connection.property_type==="domain"?"Domain property":"URL-prefix property"} · Read-only access</p><p className="mt-2 text-xs text-[var(--flight-muted)]">Last successful import: {state.connection.last_successful_sync_at?new Date(state.connection.last_successful_sync_at).toLocaleString():"Waiting for the initial 90-day import"}</p>{state.connection.last_error_message&&<p className="mt-3 text-sm text-red-700">{state.connection.last_error_message}</p>}</div><div className="flex gap-2"><a href="/api/integrations/google-search-console/connect" className="inline-flex min-h-10 items-center rounded-xl border border-[var(--flight-border)] px-3 text-sm font-semibold">Reconnect</a><Button variant="ghost" disabled={busy} onClick={disconnect}>Disconnect</Button></div></div></Card>;
}
