export const productConfig = {
  name: "SEObot",
  description: "An SEO agent that inspects, improves and verifies your website.",
  supportEmail: "support@seobot.example",
  demoMode: true,
  metadata: {
    title: "SEObot — Your SEO is being handled",
    description: "SEObot inspects your website, finds valuable work, prepares improvements and asks for approval before anything is published.",
  },
  onboardingSteps: [
    { id: "website", label: "Website" },
    { id: "discovery", label: "Discovery" },
    { id: "business", label: "Business" },
    { id: "visibility", label: "Visibility" },
    { id: "goals", label: "Goals" },
    { id: "competitors", label: "Competitors" },
    { id: "plan", label: "Plan" },
    { id: "ready", label: "Ready" },
  ],
  navigation: [
    { label: "Home", href: "/app", icon: "Home" },
    { label: "Activity", href: "/app/activity", icon: "Activity" },
    { label: "Opportunities", href: "/app/opportunities", icon: "Sparkles" },
    { label: "Keywords", href: "/app/keywords", icon: "Search" },
    { label: "Content", href: "/app/content", icon: "FileText" },
    { label: "Competitors", href: "/app/competitors", icon: "Users" },
    { label: "Website", href: "/app/website", icon: "Globe" },
    { label: "Integrations", href: "/app/integrations", icon: "Plug" },
    { label: "Settings", href: "/app/settings", icon: "Settings" },
  ],
  featureFlags: {
    realPublishing: false,
    billing: false,
    searchConsole: false,
    autonomousExecution: false,
    authentication: false,
    websiteAnalysis: false,
  },
} as const;
