export const productConfig = {
  name: "Searchhand",
  description: "An autonomous SEO agent that sets a route, prepares work and keeps search growth on course.",
  supportEmail: "support@searchhand.example",
  demoMode: true,
  metadata: {
    title: "Searchhand — Your SEO is being handled",
    description: "Searchhand inspects your website, finds valuable work, prepares improvements and asks for approval before anything is published.",
  },
  onboardingSteps: [
    { id: "website", label: "Website" },
    { id: "discovery", label: "Pre-flight" },
    { id: "business", label: "Business" },
    { id: "visibility", label: "Audience" },
    { id: "goals", label: "Destination" },
    { id: "competitors", label: "Radar" },
    { id: "plan", label: "Flight plan" },
    { id: "ready", label: "Flight Deck" },
  ],
  navigation: [
    { label: "Home", href: "/app", icon: "Home" },
    { label: "Opportunities", href: "/app/opportunities", icon: "Sparkles" },
    { label: "Website", href: "/app/website", icon: "Globe" },
    { label: "Content", href: "/app/content", icon: "FileText" },
    { label: "Competitors", href: "/app/competitors", icon: "Users" },
    { label: "Keywords", href: "/app/keywords", icon: "Search" },
    { label: "Activity", href: "/app/activity", icon: "Activity" },
    { label: "Integrations", href: "/app/integrations", icon: "Plug" },
    { label: "Settings", href: "/app/settings", icon: "Settings" },
  ],
  featureFlags: {
    realPublishing: false,
    billing: false,
    searchConsole: false,
    autonomousExecution: false,
    authentication: false,
    websiteAnalysis: false,
  },
} as const;
