import * as cheerio from "cheerio";
import { createHash } from "node:crypto";
import { normaliseCrawlUrl } from "./url-normalisation.js";
import { isWithinCrawlScope } from "./url-scope.js";
import type { ExtractedLink, HtmlExtraction } from "./crawl-result.js";
const clean=(value:string,max:number)=>value.replace(/\s+/g," ").trim().slice(0,max)||null;
type SchemaEvidence={types:Set<string>;authors:string[];published:string[];modified:string[]};
function schemaEvidence(value:unknown,result:SchemaEvidence){if(Array.isArray(value)){value.forEach(item=>schemaEvidence(item,result));return}if(!value||typeof value!=="object")return;const record=value as Record<string,unknown>;const type=record["@type"];if(typeof type==="string")result.types.add(type.slice(0,100));if(Array.isArray(type))type.filter(v=>typeof v==="string").forEach(v=>result.types.add(String(v).slice(0,100)));const author=record.author;if(typeof author==="string")result.authors.push(author);else if(author&&typeof author==="object"&&!Array.isArray(author)&&typeof (author as Record<string,unknown>).name==="string")result.authors.push(String((author as Record<string,unknown>).name));if(typeof record.datePublished==="string")result.published.push(record.datePublished);if(typeof record.dateModified==="string")result.modified.push(record.dateModified);if(record["@graph"])schemaEvidence(record["@graph"],result)}
function isoDate(value:string|null){if(!value)return null;const date=new Date(value);return Number.isNaN(date.valueOf())?null:date.toISOString()}
function normaliseContent(value:string){return value.normalize("NFKC").replace(/[\u00a0\s]+/g," ").replace(/\s+([,.;:!?])/g,"$1").trim()}
function mainText($:cheerio.CheerioAPI){const exclusions="nav,footer,header,aside,form,dialog,script,style,template,noscript,svg,[hidden],[aria-hidden='true'],[role='navigation'],[role='banner'],[role='contentinfo'],[class*='cookie' i],[id*='cookie' i],[class*='consent' i],[id*='consent' i],[class*='breadcrumb' i],[class*='sidebar' i],[class*='social-share' i]";const candidates=$("main,article,[role='main'],[itemprop='articleBody']").toArray();if(!candidates.length)candidates.push(...$("body > div,body").toArray());let best="";let bestScore=-1;for(const element of candidates){const clone=$(element).clone();clone.find(exclusions).remove();const content=normaliseContent(clone.text());if(!content)continue;const linkText=normaliseContent(clone.find("a").text()).length;const paragraphs=clone.find("p,li,h1,h2,h3,h4,h5,h6").length;const score=content.length-Math.min(linkText,content.length)*0.65+Math.min(paragraphs,100)*35;if(score>bestScore){bestScore=score;best=content}}return best.slice(0,1000000)}
export function extractHtml(html:string,pageUrl:string,startUrl:string):HtmlExtraction{
  const $=cheerio.load(html);const scripts=$("script").length;
  const schema:SchemaEvidence={types:new Set(),authors:[],published:[],modified:[]};let structuredDataValid=true;
  $("script[type='application/ld+json']").slice(0,20).each((_,element)=>{try{schemaEvidence(JSON.parse($(element).text().slice(0,200000)),schema)}catch{structuredDataValid=false}});
  const title=clean($("title").first().text(),600);const metaDescription=clean($("meta[name='description' i]").attr("content")||"",1000);const canonicalRaw=$("link[rel~='canonical' i]").first().attr("href");let canonicalUrl:string|null=null;if(canonicalRaw)try{canonicalUrl=normaliseCrawlUrl(canonicalRaw,pageUrl)}catch{canonicalUrl=canonicalRaw.slice(0,2048)}
  const robotsMeta=($("meta[name='robots' i]").attr("content")||"").toLowerCase().split(/[,\s]+/).filter(Boolean).slice(0,20);const headings:HtmlExtraction["headings"]=[];
  $("h1,h2,h3,h4,h5,h6").slice(0,100).each((position,element)=>{const value=clean($(element).text(),500);const level=Number(element.tagName.slice(1)) as 1|2|3|4|5|6;if(value)headings.push({level,text:value,position})});
  const links:ExtractedLink[]=[];$("a[href]").slice(0,1000).each((_,element)=>{if(links.length>=500)return;const href=($(element).attr("href")||"").trim();if(!href)return;const relValues=($(element).attr("rel")||"").toLowerCase().split(/\s+/).filter(Boolean).slice(0,20);let type:ExtractedLink["type"]="unsupported",normalisedTargetUrl:string|null=null,targetUrl=href.slice(0,2048);if(href.startsWith("#"))type="fragment";else if(/^mailto:/i.test(href))type="mailto";else if(/^tel:/i.test(href))type="telephone";else try{normalisedTargetUrl=normaliseCrawlUrl(href,pageUrl);targetUrl=normalisedTargetUrl;type=isWithinCrawlScope(normalisedTargetUrl,startUrl)?"internal":"external"}catch{type="unsupported"}links.push({targetUrl,normalisedTargetUrl,type,anchorText:clean($(element).text(),500),relValues,followed:type==="internal"&&!relValues.includes("nofollow")})});
  const images:HtmlExtraction["images"]=[];$("main img,article img,[role='main'] img,body img").each((_,element)=>{if(images.length>=200)return false;const raw=$(element).attr("src")||$(element).attr("data-src");if(!raw)return;let src:string;try{src=new URL(raw,pageUrl).toString().slice(0,2048)}catch{return}if(images.some(image=>image.src===src))return;images.push({src,alt:clean($(element).attr("alt")||"",1000),title:clean($(element).attr("title")||"",1000)})});
  const mainContent=mainText($);const wordCount=mainContent?mainContent.split(/\s+/).length:0;const possibleJsRendering=wordCount<80&&scripts>=5&&/(?:id=["'](?:root|app|__next)|data-reactroot)/i.test(html);const author=clean($("meta[name='author' i]").attr("content")||schema.authors[0]||"",300);const publishedAt=isoDate($("meta[property='article:published_time' i],meta[name='date' i]").first().attr("content")||schema.published[0]||null);const modifiedAt=isoDate($("meta[property='article:modified_time' i],meta[name='last-modified' i]").first().attr("content")||schema.modified[0]||null);
  return{title,metaDescription,canonicalUrl,robotsMeta,language:clean($("html").attr("lang")||"",30),headings,h1Count:headings.filter(h=>h.level===1).length,h2Count:headings.filter(h=>h.level===2).length,wordCount,structuredDataTypes:[...schema.types].slice(0,50),structuredDataValid,links,mainContent,contentHash:createHash("sha256").update(mainContent).digest("hex"),author,publishedAt,modifiedAt,images,possibleJsRendering};
}
