export const COMPOSIO_SDK_VERSION = "0.14.0";
export const SHOPIFY_TOOLKIT_VERSION = "20260721_00";
export const SHOPIFY_CREATE_ARTICLE_ACTION = "SHOPIFY_CREATE_ARTICLE";
export const SHOPIFY_GET_ARTICLE_ACTION = "SHOPIFY_GET_ARTICLE";
export const SHOPIFY_QUERY_SHOP_ACTION = "SHOPIFY_QUERY_SHOP";
export const SHOPIFY_TEST_DRAFT_IDEMPOTENCY_KEY = "shopify_connection_test_v1";
