import type { SupabaseClient } from "@supabase/supabase-js";
import { runPageIntelligenceJob } from "../search-intelligence/page-job.js";
import { runGscSyncJob } from "../gsc/importer.js";
import { runRecommendationJob } from "../search-intelligence/recommendation-job.js";

export type ClaimedIntelligenceJob={job_id:string;project_id:string;job_type:"page_intelligence_analysis"|"gsc_initial_sync"|"gsc_daily_sync"|"generate_seo_recommendations"|"refresh_seo_recommendations";input_payload:Record<string,unknown>;attempt:number;max_attempts:number};
export async function claimIntelligenceJob(client:SupabaseClient,workerId:string,lockMinutes:number){const {data,error}=await client.rpc("claim_next_intelligence_job",{claiming_worker_id:workerId,lock_minutes:lockMinutes});if(error)throw error;return data as ClaimedIntelligenceJob|null}
export async function heartbeatIntelligenceJob(client:SupabaseClient,jobId:string,workerId:string,progress:number,output:Record<string,unknown>|undefined,lockMinutes:number){const {error}=await client.rpc("heartbeat_intelligence_job",{target_job_id:jobId,claiming_worker_id:workerId,job_progress:progress,output:output||null,lock_minutes:lockMinutes});if(error)throw error}
export async function completeIntelligenceJob(client:SupabaseClient,jobId:string,workerId:string,output:Record<string,unknown>){const {error}=await client.rpc("complete_intelligence_job",{target_job_id:jobId,claiming_worker_id:workerId,output});if(error)throw error}
export async function failIntelligenceJob(client:SupabaseClient,jobId:string,workerId:string,message:string,retryable:boolean){const {error}=await client.rpc("fail_intelligence_job",{target_job_id:jobId,claiming_worker_id:workerId,safe_error:message,retryable});if(error)throw error}
const string=(value:unknown,name:string)=>{if(typeof value!=="string"||!value)throw new Error(`Intelligence job is missing ${name}.`);return value};
export async function executeIntelligenceJob(client:SupabaseClient,job:ClaimedIntelligenceJob,workerId:string,lockMinutes:number){const input=job.input_payload;switch(job.job_type){case"page_intelligence_analysis":return runPageIntelligenceJob(client,{project_id:job.project_id,website_id:string(input.website_id,"website_id"),crawl_run_id:string(input.crawl_run_id,"crawl_run_id")});case"gsc_initial_sync":case"gsc_daily_sync":return runGscSyncJob(client,{connection_id:string(input.connection_id,"connection_id"),sync_type:job.job_type==="gsc_initial_sync"?"initial":"daily"},job.job_id,(progress,output)=>heartbeatIntelligenceJob(client,job.job_id,workerId,progress,output,lockMinutes));case"generate_seo_recommendations":case"refresh_seo_recommendations":return runRecommendationJob(client,{project_id:job.project_id,website_id:string(input.website_id,"website_id"),crawl_run_id:typeof input.crawl_run_id==="string"?input.crawl_run_id:undefined,connection_id:typeof input.connection_id==="string"?input.connection_id:undefined});default:throw new Error(`Unsupported intelligence job type: ${String(job.job_type)}`)}}
