import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getOptionalUser } from "@/lib/auth/server";
import { getProjectSnapshot } from "@/lib/data/project-snapshot";
import { onboardingDraftSchema, onboardingPayloadSchema } from "@/lib/validation/backend";
import { normaliseWebsite } from "@/lib/onboarding/schema";

const saveSchema=z.object({data:onboardingDraftSchema,nextStep:z.number().int().min(0).max(7)});
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||"project";
function domain(url:string){return new URL(url).hostname.toLowerCase().replace(/^www\./,"")}
async function authClient(){const user=await getOptionalUser();const supabase=await createClient();return user&&supabase?{user,supabase}:null}

export async function POST(request:Request){const auth=await authClient();if(!auth)return NextResponse.json({error:"Authentication required."},{status:401});const body=await request.json().catch(()=>null);const parsed=saveSchema.safeParse(body);if(!parsed.success)return NextResponse.json({error:"Check the onboarding details.",fieldErrors:parsed.error.flatten().fieldErrors},{status:400});const existing=await getProjectSnapshot();if(existing)return NextResponse.json(existing);const data={...parsed.data.data,websiteUrl:normaliseWebsite(parsed.data.data.websiteUrl),currentStep:parsed.data.nextStep};const result=await auth.supabase.rpc("create_initial_project",{workspace_name:`${data.businessName} workspace`,project_name:data.businessName,project_slug:slugify(data.businessName),website_url:data.websiteUrl,website_domain:domain(data.websiteUrl),draft:data});const created=(Array.isArray(result.data)?result.data[0]:result.data) as {project_id:string}|null;if(result.error||!created)return NextResponse.json({error:"We couldn’t create the private workspace. Please try again."},{status:400});await auth.supabase.from("onboarding_progress").update({current_step:data.currentStep+1,draft_data:data,last_saved_at:new Date().toISOString()}).eq("project_id",created.project_id);await auth.supabase.from("projects").update({onboarding_step:data.currentStep+1,onboarding_status:"in_progress"}).eq("id",created.project_id);return NextResponse.json(await getProjectSnapshot(),{status:201})}

export async function PUT(request:Request){const auth=await authClient();if(!auth)return NextResponse.json({error:"Authentication required."},{status:401});const body=await request.json().catch(()=>null);const parsed=saveSchema.safeParse(body);if(!parsed.success)return NextResponse.json({error:"Check the onboarding details.",fieldErrors:parsed.error.flatten().fieldErrors},{status:400});const snapshot=await getProjectSnapshot();if(!snapshot)return NextResponse.json({error:"Create the project before saving progress."},{status:404});const data={...parsed.data.data,currentStep:parsed.data.nextStep};const {error}=await auth.supabase.from("onboarding_progress").update({current_step:data.currentStep+1,draft_data:data,last_saved_at:new Date().toISOString()}).eq("project_id",snapshot.project.id);if(error)return NextResponse.json({error:"Progress could not be saved. Your answers remain on screen."},{status:400});await auth.supabase.from("projects").update({onboarding_step:data.currentStep+1,onboarding_status:"in_progress"}).eq("id",snapshot.project.id);return NextResponse.json({success:true,data})}

export async function PATCH(request:Request){const auth=await authClient();if(!auth)return NextResponse.json({error:"Authentication required."},{status:401});const body=await request.json().catch(()=>null);const parsed=onboardingPayloadSchema.safeParse(body?.data);if(!parsed.success)return NextResponse.json({error:"Complete the required onboarding details.",fieldErrors:parsed.error.flatten().fieldErrors},{status:400});const snapshot=await getProjectSnapshot();if(!snapshot)return NextResponse.json({error:"Project not found."},{status:404});const data={...parsed.data,domain:domain(parsed.data.websiteUrl),completed:true};const {error}=await auth.supabase.rpc("complete_project_onboarding",{target_project_id:snapshot.project.id,payload:data});if(error)return NextResponse.json({error:"The workspace could not be completed. Nothing was partially saved."},{status:400});return NextResponse.json(await getProjectSnapshot())}
