-- Northstar V1 foundation. Run through Supabase migrations; never use the service role in the browser.
create extension if not exists "pgcrypto";
create type public.workspace_role as enum ('owner', 'member');
create type public.job_status as enum ('queued','running','waiting_for_input','waiting_for_approval','completed','failed','cancelled');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, avatar_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,avatar_url) values(new.id,new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'avatar_url') on conflict(id) do nothing; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table public.workspaces (id uuid primary key default gen_random_uuid(), name text not null, created_by uuid not null references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table public.workspace_members (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role public.workspace_role not null default 'member', created_at timestamptz default now(), unique(workspace_id,user_id));
create table public.projects (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, name text not null, slug text not null, status text not null default 'active', onboarding_status text not null default 'in_progress', onboarding_step smallint not null default 1 check(onboarding_step between 1 and 8), onboarding_completed_at timestamptz, approval_preference text default 'review_important', created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,slug));
create table public.websites (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, url text not null, normalised_url text not null, domain text not null, display_name text, favicon_url text, title text, meta_description text, robots_txt_status text default 'unknown', sitemap_status text default 'unknown', last_analysed_at timestamptz, analysis_status text default 'idle', analysis_error text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(project_id,domain));
create table public.website_discoveries (id uuid primary key default gen_random_uuid(), website_id uuid not null references public.websites(id) on delete cascade, discovery_type text not null, label text not null, url text, status text not null, source text not null, metadata jsonb not null default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table public.business_profiles (id uuid primary key default gen_random_uuid(), project_id uuid not null unique references public.projects(id) on delete cascade, business_name text, description text, industry text, products_services text[] default '{}', target_customers text, locations text[] default '{}', business_model text, tone text, primary_conversion text, audience_scope text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.project_goals (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, goal_type text not null, priority smallint not null, created_at timestamptz default now(), unique(project_id,goal_type));
create table public.competitors (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null, domain text not null, url text not null, notes text, status text default 'confirmed', source text not null, confirmed_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.opportunities (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, title text not null, description text not null, category text not null, impact text not null, effort text not null, confidence text not null, status text not null default 'new', source text not null, requires_real_data boolean not null default false, related_url text, metadata jsonb not null default '{}', discovered_at timestamptz default now(), created_at timestamptz default now(), updated_at timestamptz default now());
create table public.keyword_topics (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, keyword text not null, intent text, relevance text, status text default 'hypothesis', source text not null, is_hypothesis boolean not null default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.seo_jobs (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, job_type text not null, title text not null, status public.job_status not null default 'queued', priority smallint not null default 3, input_payload jsonb not null default '{}', output_payload jsonb not null default '{}', progress smallint check(progress between 0 and 100), attempt_count integer not null default 0, error_message text, scheduled_at timestamptz, started_at timestamptz, completed_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.activities (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, title text not null, description text, activity_type text not null, status text not null, related_entity_type text, related_entity_id uuid, metadata jsonb not null default '{}', destination_url text, created_at timestamptz default now());
create table public.integrations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, provider text not null, status text not null default 'unavailable', configuration jsonb not null default '{}', connected_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now(), unique(project_id,provider));

alter table public.profiles enable row level security; alter table public.workspaces enable row level security; alter table public.workspace_members enable row level security; alter table public.projects enable row level security; alter table public.websites enable row level security; alter table public.website_discoveries enable row level security; alter table public.business_profiles enable row level security; alter table public.project_goals enable row level security; alter table public.competitors enable row level security; alter table public.opportunities enable row level security; alter table public.keyword_topics enable row level security; alter table public.seo_jobs enable row level security; alter table public.activities enable row level security; alter table public.integrations enable row level security;

create or replace function public.is_workspace_member(target uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from workspace_members where workspace_id=target and user_id=auth.uid()) $$;
create policy "profiles own row" on public.profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy "members read workspaces" on public.workspaces for select using (public.is_workspace_member(id));
create policy "users create workspaces" on public.workspaces for insert with check (created_by=auth.uid());
create policy "members read memberships" on public.workspace_members for select using (user_id=auth.uid() or public.is_workspace_member(workspace_id));
create policy "users create own membership" on public.workspace_members for insert with check (user_id=auth.uid());
create policy "members manage projects" on public.projects for all using (public.is_workspace_member(workspace_id)) with check (public.is_workspace_member(workspace_id));
create or replace function public.can_access_project(target uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from projects p where p.id=target and public.is_workspace_member(p.workspace_id)) $$;
create policy "members manage websites" on public.websites for all using (public.can_access_project(project_id)) with check (public.can_access_project(project_id));
create policy "members manage profiles" on public.business_profiles for all using (public.can_access_project(project_id)) with check (public.can_access_project(project_id));
create policy "members manage goals" on public.project_goals for all using (public.can_access_project(project_id)) with check (public.can_access_project(project_id));
create policy "members manage competitors" on public.competitors for all using (public.can_access_project(project_id)) with check (public.can_access_project(project_id));
create policy "members manage opportunities" on public.opportunities for all using (public.can_access_project(project_id)) with check (public.can_access_project(project_id));
create policy "members manage topics" on public.keyword_topics for all using (public.can_access_project(project_id)) with check (public.can_access_project(project_id));
create policy "members manage jobs" on public.seo_jobs for all using (public.can_access_project(project_id)) with check (public.can_access_project(project_id));
create policy "members manage activities" on public.activities for all using (public.can_access_project(project_id)) with check (public.can_access_project(project_id));
create policy "members manage integrations" on public.integrations for all using (public.can_access_project(project_id)) with check (public.can_access_project(project_id));
create policy "members manage discoveries" on public.website_discoveries for all using (exists(select 1 from websites w where w.id=website_id and public.can_access_project(w.project_id))) with check (exists(select 1 from websites w where w.id=website_id and public.can_access_project(w.project_id)));
