import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { analysePageDeterministically, PAGE_INTELLIGENCE_VERSION } from "./page-analyzer.js";

export async function runPageIntelligenceJob(client:SupabaseClient,input:{project_id:string;website_id:string;crawl_run_id:string}){
  const {data:scope,error:scopeError}=await client.from("crawl_runs").select("id").eq("id",input.crawl_run_id).eq("project_id",input.project_id).eq("website_id",input.website_id).maybeSingle();if(scopeError)throw scopeError;if(!scope)throw new Error("Page intelligence job scope does not match the crawl run.");
  const [{data:project,error:projectError},{data:profile,error:profileError},{data:snapshots,error:snapshotError}]=await Promise.all([
    client.from("projects").select("workspace_id").eq("id",input.project_id).single(),
    client.from("business_profiles").select("products_services,locations,main_location,target_customers").eq("project_id",input.project_id).maybeSingle(),
    client.from("crawl_page_snapshots").select("id,website_page_id,requested_url,final_url,title,meta_description,indexable,word_count,structured_data_types,content_hash,main_content,incoming_internal_link_count,outgoing_internal_link_count").eq("crawl_run_id",input.crawl_run_id).not("website_page_id","is",null).order("created_at"),
  ]);if(projectError)throw projectError;if(profileError)throw profileError;if(snapshotError)throw snapshotError;
  const snapshotIds=(snapshots||[]).map(snapshot=>snapshot.id);const {data:headings,error:headingsError}=snapshotIds.length?await client.from("page_headings").select("crawl_page_snapshot_id,heading_level,heading_text,position").in("crawl_page_snapshot_id",snapshotIds).order("position"):{data:[],error:null};if(headingsError)throw headingsError;
  let analysed=0,skipped=0;for(const snapshot of snapshots||[]){if(!snapshot.website_page_id)continue;const contentHash=snapshot.content_hash||createHash("sha256").update([snapshot.title,snapshot.meta_description,...(headings||[]).filter(heading=>heading.crawl_page_snapshot_id===snapshot.id).map(heading=>heading.heading_text)].join("|")).digest("hex");const {data:existing,error:existingError}=await client.from("page_intelligence").select("id").eq("website_page_id",snapshot.website_page_id).eq("content_hash",contentHash).eq("analysis_version",PAGE_INTELLIGENCE_VERSION).maybeSingle();if(existingError)throw existingError;if(existing){skipped++;continue}const result=analysePageDeterministically({url:snapshot.final_url||snapshot.requested_url,title:snapshot.title,metaDescription:snapshot.meta_description,headings:(headings||[]).filter(heading=>heading.crawl_page_snapshot_id===snapshot.id).map(heading=>({level:heading.heading_level,text:heading.heading_text})),mainContent:snapshot.main_content||"",wordCount:snapshot.word_count||0,structuredDataTypes:snapshot.structured_data_types||[],indexable:snapshot.indexable,incomingInternalLinkCount:snapshot.incoming_internal_link_count||0,outgoingInternalLinkCount:snapshot.outgoing_internal_link_count||0,productsServices:profile?.products_services||[],locations:[...(profile?.locations||[]),...(profile?.main_location?[profile.main_location]:[])],targetCustomers:profile?.target_customers||null});const {error}=await client.from("page_intelligence").insert({workspace_id:project.workspace_id,project_id:input.project_id,website_id:input.website_id,website_page_id:snapshot.website_page_id,crawl_run_id:input.crawl_run_id,page_snapshot_id:snapshot.id,analysis_version:PAGE_INTELLIGENCE_VERSION,content_hash:contentHash,page_type:result.pageType,primary_topic:result.primaryTopic,secondary_topics:result.secondaryTopics,search_intent:result.searchIntent,funnel_stage:result.funnelStage,products_services:result.productsServices,locations:result.locations,audience_types:result.audienceTypes,page_purpose_summary:result.pagePurposeSummary,content_quality_score:result.contentQualityScore,content_completeness_score:result.contentCompletenessScore,recommended_target_query:result.recommendedTargetQuery,confidence:result.confidence,evidence:result.evidence,analysis_status:"completed"});if(error)throw error;await client.from("website_pages").update({page_type:result.pageType}).eq("id",snapshot.website_page_id).eq("project_id",input.project_id);analysed++}
  await client.from("activities").insert({project_id:input.project_id,activity_type:"website_pages_analysed",title:"Website pages understood",description:`Searchhand analysed ${analysed} changed page${analysed===1?"":"s"} and reused ${skipped} current result${skipped===1?"":"s"}.`,status:"completed",related_entity_type:"crawl_run",related_entity_id:input.crawl_run_id,metadata:{analysed,skipped,analysis_version:PAGE_INTELLIGENCE_VERSION}});
  const sourceVersion=createHash("sha256").update(`${PAGE_INTELLIGENCE_VERSION}|${input.crawl_run_id}|${analysed}|${skipped}`).digest("hex");await client.from("seo_jobs").insert({project_id:input.project_id,job_type:"generate_seo_recommendations",status:"queued",priority:70,progress:0,input_payload:{website_id:input.website_id,crawl_run_id:input.crawl_run_id,page_intelligence_version:sourceVersion},max_attempts:3,dedupe_key:`recommendations:${input.website_id}:${sourceVersion}`,next_attempt_at:new Date().toISOString(),required_capability:"search_intelligence"});
  return{analysed,skipped,analysisVersion:PAGE_INTELLIGENCE_VERSION};
}
