import Link from "next/link";
import { AlertTriangle, CheckCircle2, ExternalLink, FileText, KeyRound, ShieldCheck } from "lucide-react";
import { WordPressConnectForm, WordPressConnectionActions } from "@/components/integrations/wordpress-actions";
import { Badge, Card, PageHeader } from "@/components/ui";
import { getWordPressPublishingServerEnv } from "@/lib/config/publishing-env";
import { listWordPressConnections } from "@/lib/publishing/wordpress/wordpress-connections";
import type { SafePublishingConnection } from "@/lib/publishing/types";

export const dynamic = "force-dynamic";
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value)) : "Not yet";
const tone = (status: string): "green" | "amber" | "red" | "neutral" => status === "connected" ? "green" : status === "pending" ? "amber" : status === "error" || status === "needs_reauthentication" ? "red" : "neutral";
const label = (status: string) => ({ connected: "Connected", pending: "Connecting", needs_reauthentication: "Needs attention", error: "Needs attention", disconnected: "Disconnected", revoked: "Disconnected" }[status] || status);

function ConnectionCard({ connection }: { connection: SafePublishingConnection }) {
  const connected = connection.status === "connected";
  return <Card className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e7f3ed] text-[var(--flight-green)]"><FileText size={21}/></span><div className="min-w-0"><h2 className="font-semibold">{connection.storeName || "WordPress website"}</h2>{connection.storeUrl && <Link href={connection.storeUrl} target="_blank" rel="noreferrer" className="mt-1 inline-flex max-w-full items-center gap-1 break-all text-sm text-[var(--flight-blue)]">{connection.storeUrl}<ExternalLink size={12}/></Link>}</div></div><Badge tone={tone(connection.status)}>{label(connection.status)}</Badge></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-4"><div><dt className="text-xs text-[var(--muted)]">Connected account</dt><dd className="mt-1 font-medium">{connection.accountName || "WordPress user"}</dd></div><div><dt className="text-xs text-[var(--muted)]">Publishing mode</dt><dd className="mt-1 font-medium">Drafts only</dd></div><div><dt className="text-xs text-[var(--muted)]">Connected</dt><dd className="mt-1 font-medium">{date(connection.connectedAt)}</dd></div><div><dt className="text-xs text-[var(--muted)]">Last checked</dt><dd className="mt-1 font-medium">{date(connection.lastCheckedAt)}</dd></div></dl>{connection.errorMessage && <p role="alert" className="mt-4 flex gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-800"><AlertTriangle size={16}/>{connection.errorMessage}</p>}{connection.testDraftStatus && <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#f2f1ec] p-3 text-sm"><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[var(--flight-green)]"/>Test draft: {connection.testDraftStatus}</span>{(connection.testDraftAdminUrl || connection.testDraftUrl) && <Link href={connection.testDraftAdminUrl || connection.testDraftUrl || "#"} target="_blank" rel="noreferrer" className="font-semibold text-[var(--flight-blue)]">Edit in WordPress</Link>}</div>}<WordPressConnectionActions connectionId={connection.id} connected={connected} siteUrl={connection.storeUrl} hasTestDraft={Boolean(connection.testDraftStatus)}/></Card>;
}

export default async function WordPressIntegrationPage() {
  const configured = Boolean(getWordPressPublishingServerEnv());
  let connections: SafePublishingConnection[] = [];
  let loadError: string | null = null;
  if (configured) try { connections = await listWordPressConnections(); } catch { loadError = "WordPress connections could not be loaded. Check the server configuration and database migration."; }
  return <><PageHeader eyebrow="Publishing destination" title="WordPress" description="Connect with a WordPress Application Password, then send approved Searchhand content as drafts."/><div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card className="p-5 sm:p-6"><div className="flex items-start gap-3"><KeyRound className="mt-0.5 text-[var(--flight-green)]"/><div><h2 className="font-semibold">Connect WordPress</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">Credentials are encrypted before storage and never shown again. Do not enter your normal WordPress password.</p></div></div>{configured ? <div className="mt-5"><WordPressConnectForm/></div> : <p role="alert" className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Add APP_URL, INTEGRATION_ENCRYPTION_KEY and the Supabase server credentials, then apply the WordPress migration.</p>}</Card><Card className="p-5 sm:p-6"><h2 className="font-semibold">Create an Application Password</h2><ol className="mt-4 space-y-3 text-sm leading-6 text-[var(--muted)]"><li>1. Sign in to WordPress Admin.</li><li>2. Open Users → Profile.</li><li>3. Find Application Passwords.</li><li>4. Enter “Searchhand” and add it.</li><li>5. Copy the generated password and paste it here.</li></ol><div className="mt-5 flex gap-2 rounded-xl bg-[#e7f3ed] p-3 text-sm text-[var(--flight-green)]"><ShieldCheck size={17} className="shrink-0"/>An Editor account is enough. Searchhand enforces draft status on the server.</div></Card></div>{loadError ? <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{loadError}</p> : connections.length ? <div className="mt-5 space-y-4">{connections.map((connection) => <ConnectionCard key={connection.id} connection={connection}/>)}</div> : configured ? <p className="mt-5 rounded-xl bg-[#f2f1ec] p-4 text-sm text-[var(--muted)]">No WordPress websites connected yet.</p> : null}</>;
}
