export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
type Table<Row,Insert=Partial<Row>,Update=Partial<Insert>> = { Row: Row; Insert: Insert; Update: Update; Relationships: [] };
type Timestamps = { created_at:string; updated_at:string };
type ProjectChild = { id:string; project_id:string; created_at:string };

export type Database = { public: {
  Tables: {
    profiles: Table<{id:string;full_name:string|null;avatar_url:string|null}&Timestamps>;
    workspaces: Table<{id:string;name:string;created_by:string}&Timestamps>;
    workspace_members: Table<{id:string;workspace_id:string;user_id:string;role:"owner"|"member";created_at:string}>;
    projects: Table<{id:string;workspace_id:string;created_by:string;name:string;slug:string;status:"active"|"paused"|"archived";is_primary:boolean;onboarding_status:"not_started"|"in_progress"|"completed";onboarding_step:number;onboarding_completed_at:string|null}&Timestamps>;
    websites: Table<ProjectChild&{url:string;normalised_url:string;domain:string;display_name:string|null;is_primary:boolean;title:string|null;meta_description:string|null;favicon_url:string|null;robots_txt_status:string;sitemap_status:string;analysis_status:string;analysis_error:string|null;last_analysed_at:string|null;crawl_authorised_at:string|null;updated_at:string}>;
    onboarding_progress: Table<{project_id:string;current_step:number;draft_data:Json;completed:boolean;last_saved_at:string}&Timestamps>;
    business_profiles: Table<ProjectChild&{business_name:string;description:string|null;industry:string|null;products_services:string[];target_customers:string|null;locations:string[];main_location:string|null;business_model:string|null;brand_tone:string|null;primary_conversion:string|null;audience_scope:"local"|"national"|"international"|null;updated_at:string}>;
    project_goals: Table<ProjectChild&{goal_type:string;priority:number|null}>;
    project_settings: Table<ProjectChild&{approval_mode:"review_all"|"review_important"|"autonomous_within_rules";timezone:string|null;weekly_summary_enabled:boolean;updated_at:string}>;
    competitors: Table<ProjectChild&{name:string;domain:string|null;url:string|null;notes:string|null;status:"confirmed"|"inactive";source:"user"|"onboarding_suggestion"|"future_provider";confirmed_at:string|null;updated_at:string}>;
    opportunities: Table<ProjectChild&{title:string;description:string;category:string;impact:string;effort:string;confidence:string;status:"new"|"planned"|"in_progress"|"waiting_for_approval"|"completed"|"dismissed";source:"onboarding_seed"|"user";requires_real_data:boolean;related_url:string|null;metadata:Json;discovered_at:string;updated_at:string}>;
    keyword_topics: Table<ProjectChild&{topic:string;intent:string|null;relevance:string|null;status:string;source:string;is_hypothesis:boolean;updated_at:string}>;
    content_items: Table<ProjectChild&{title:string;content_type:string;purpose:string|null;target_customer:string|null;status:"idea"|"planned"|"dismissed"|"archived";source:"onboarding_seed"|"user";target_topic_id:string|null;target_url:string|null;brief:string|null;draft:string|null;published_url:string|null;updated_at:string}>;
    seo_jobs: Table<ProjectChild&{job_type:string;status:string;priority:number;progress:number|null;input_payload:Json;output_payload:Json;attempt_count:number;error_message:string|null;scheduled_for:string|null;started_at:string|null;completed_at:string|null;updated_at:string;crawl_run_id:string|null;worker_id:string|null;locked_at:string|null;lock_expires_at:string|null;heartbeat_at:string|null;cancel_requested_at:string|null;max_attempts:number;next_attempt_at:string|null;dedupe_key:string|null}>;
    activities: Table<ProjectChild&{activity_type:string;title:string;description:string|null;status:string;related_entity_type:string|null;related_entity_id:string|null;metadata:Json}>;
    approval_requests: Table<ProjectChild&{entity_type:string;entity_id:string|null;status:string;requested_at:string;resolved_at:string|null;resolved_by:string|null;notes:string|null;updated_at:string}>;
    integrations: Table<ProjectChild&{provider:string;status:string;external_account_id:string|null;configuration:Json;connected_at:string|null;last_synced_at:string|null;error_message:string|null;updated_at:string}>;
    crawl_settings: Table<{id:string;website_id:string;max_pages:number;max_depth:number;concurrency:number;request_delay_ms:number;respect_robots:boolean;include_subdomains:boolean;query_parameter_policy:string}&Timestamps>;
    crawl_runs: Table<ProjectChild&{website_id:string;created_by:string|null;status:"queued"|"running"|"completed"|"completed_with_warnings"|"failed"|"cancelled";trigger_type:"onboarding"|"manual"|"retry"|"future_scheduled";max_pages:number;max_depth:number;pages_discovered:number;pages_queued:number;pages_fetched:number;pages_succeeded:number;pages_failed:number;pages_skipped:number;issues_found:number;current_url:string|null;heartbeat_at:string|null;started_at:string|null;completed_at:string|null;cancel_requested_at:string|null;error_summary:string|null;configuration:Json;updated_at:string}>;
    website_pages: Table<ProjectChild&{website_id:string;url:string;normalised_url:string;final_url:string|null;path:string|null;page_type:string;latest_http_status:number|null;latest_content_type:string|null;latest_title:string|null;latest_meta_description:string|null;latest_canonical_url:string|null;latest_indexable:boolean|null;latest_indexability_reason:string|null;latest_h1_count:number|null;latest_h2_count:number|null;latest_word_count:number|null;latest_language:string|null;latest_content_hash:string|null;latest_structured_data_types:string[];last_seen_crawl_id:string|null;first_seen_at:string;last_seen_at:string;updated_at:string}>;
    crawl_page_snapshots: Table<{id:string;crawl_run_id:string;website_page_id:string|null;requested_url:string;normalised_url:string;final_url:string|null;http_status:number|null;content_type:string|null;response_time_ms:number|null;response_bytes:number|null;redirect_count:number;title:string|null;meta_description:string|null;canonical_url:string|null;robots_meta:string[];x_robots_tag:string[];indexable:boolean|null;indexability_reason:string|null;h1_count:number|null;h2_count:number|null;word_count:number|null;language:string|null;structured_data_types:string[];content_hash:string|null;fetch_error_code:string|null;fetch_error_message:string|null;crawl_depth:number;source_type:string;created_at:string}>;
    page_headings: Table<{id:string;crawl_page_snapshot_id:string;website_page_id:string|null;heading_level:number;heading_text:string;position:number;created_at:string}>;
    page_links: Table<{id:string;crawl_run_id:string;crawl_page_snapshot_id:string;source_page_id:string|null;target_page_id:string|null;target_url:string;normalised_target_url:string|null;link_type:string;anchor_text:string|null;rel_values:string[];is_followed:boolean;created_at:string}>;
    sitemaps: Table<{id:string;crawl_run_id:string;website_id:string;url:string;sitemap_type:string;http_status:number|null;url_count:number|null;content_hash:string|null;last_modified_max:string|null;fetch_error_code:string|null;fetch_error_message:string|null;created_at:string}>;
    robots_snapshots: Table<{id:string;crawl_run_id:string;website_id:string;url:string;http_status:number|null;content:string|null;content_hash:string|null;fetch_error_code:string|null;fetch_error_message:string|null;fetched_at:string;created_at:string}>;
    robots_rules: Table<{id:string;robots_snapshot_id:string;user_agent:string;directive:string;value:string|null;position:number;created_at:string}>;
    seo_issues: Table<ProjectChild&{website_id:string;website_page_id:string|null;crawl_run_id:string;fingerprint:string;issue_type:string;severity:"error"|"warning"|"information";title:string;description:string;recommendation:string|null;evidence:Json;status:"open"|"resolved"|"ignored";first_seen_at:string;last_seen_at:string;resolved_at:string|null;ignored_at:string|null;ignored_by:string|null;updated_at:string}>;
    worker_heartbeats: Table<{worker_id:string;worker_type:string;status:string;current_job_id:string|null;last_heartbeat_at:string;metadata:Json}&Timestamps>;
  };
  Views: Record<string,never>;
  Functions: {
    is_workspace_member:{Args:{target_workspace_id:string};Returns:boolean};
    is_workspace_owner:{Args:{target_workspace_id:string};Returns:boolean};
    can_access_project:{Args:{target_project_id:string};Returns:boolean};
    create_initial_project:{Args:{workspace_name:string;project_name:string;project_slug:string;website_url:string;website_domain:string;draft?:Json};Returns:{workspace_id:string;project_id:string;website_id:string}[]};
    complete_project_onboarding:{Args:{target_project_id:string;payload:Json};Returns:string};
    enqueue_website_crawl:{Args:{target_website_id:string;requested_trigger:string};Returns:string};
    request_crawl_cancellation:{Args:{target_run_id:string};Returns:boolean};
    set_issue_ignored:{Args:{target_issue_id:string;should_ignore:boolean};Returns:boolean};
  };
  Enums: Record<string,never>;
  CompositeTypes: { initial_project_result:{workspace_id:string;project_id:string;website_id:string} };
}};
